// CollectorService ingests compressed log batches from agents.
// The manager treats payload bytes as opaque and fans them out to configured
// destinations without buffering or parsing records.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cicd_sensor/manager/v1/collector.proto

package managerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogType identifies the JSONL log encoded in an ingest batch.
type LogType int32

const (
	LogType_LOG_TYPE_UNSPECIFIED   LogType = 0
	LogType_LOG_TYPE_DETECTION     LogType = 1
	LogType_LOG_TYPE_RUNTIME_EVENT LogType = 2
	LogType_LOG_TYPE_SUMMARY       LogType = 3
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_TYPE_UNSPECIFIED",
		1: "LOG_TYPE_DETECTION",
		2: "LOG_TYPE_RUNTIME_EVENT",
		3: "LOG_TYPE_SUMMARY",
	}
	LogType_value = map[string]int32{
		"LOG_TYPE_UNSPECIFIED":   0,
		"LOG_TYPE_DETECTION":     1,
		"LOG_TYPE_RUNTIME_EVENT": 2,
		"LOG_TYPE_SUMMARY":       3,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_cicd_sensor_manager_v1_collector_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_cicd_sensor_manager_v1_collector_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_collector_proto_rawDescGZIP(), []int{0}
}

// Scope identifies which ownership scope produced an ingest batch.
type Scope int32

const (
	Scope_SCOPE_UNSPECIFIED Scope = 0
	Scope_SCOPE_HOST        Scope = 1
	Scope_SCOPE_PROJECT     Scope = 2
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		1: "SCOPE_HOST",
		2: "SCOPE_PROJECT",
	}
	Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED": 0,
		"SCOPE_HOST":        1,
		"SCOPE_PROJECT":     2,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_cicd_sensor_manager_v1_collector_proto_enumTypes[1].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_cicd_sensor_manager_v1_collector_proto_enumTypes[1]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_collector_proto_rawDescGZIP(), []int{1}
}

// IngestLogBatch carries one agent-side batch of gzip-compressed JSONL records.
type IngestLogBatch struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	JobIdentity *JobIdentity           `protobuf:"bytes,1,opt,name=job_identity,json=jobIdentity,proto3" json:"job_identity,omitempty"`
	Scope       Scope                  `protobuf:"varint,2,opt,name=scope,proto3,enum=cicd_sensor.manager.v1.Scope" json:"scope,omitempty"`
	LogType     LogType                `protobuf:"varint,3,opt,name=log_type,json=logType,proto3,enum=cicd_sensor.manager.v1.LogType" json:"log_type,omitempty"`
	// compressed_jsonl is gzip-compressed JSONL. The manager writes these bytes
	// verbatim and only checks the gzip magic bytes.
	CompressedJsonl []byte `protobuf:"bytes,4,opt,name=compressed_jsonl,json=compressedJsonl,proto3" json:"compressed_jsonl,omitempty"`
	// flush_at is the UTC wallclock time when the agent first flushed this
	// batch. The manager formats it as YYYYMMDDhhmmssNNN (UTC, milliseconds
	// zero-padded) and uses it as the leading object-key segment for sub-hour
	// disambiguation and chronological lexical sort. Retries must reuse the
	// original value so the same batch overwrites the same object key.
	// Sub-millisecond precision is truncated.
	FlushAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=flush_at,json=flushAt,proto3" json:"flush_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogBatch) Reset() {
	*x = IngestLogBatch{}
	mi := &file_cicd_sensor_manager_v1_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogBatch) ProtoMessage() {}

func (x *IngestLogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogBatch.ProtoReflect.Descriptor instead.
func (*IngestLogBatch) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_collector_proto_rawDescGZIP(), []int{0}
}

func (x *IngestLogBatch) GetJobIdentity() *JobIdentity {
	if x != nil {
		return x.JobIdentity
	}
	return nil
}

func (x *IngestLogBatch) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_UNSPECIFIED
}

func (x *IngestLogBatch) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_LOG_TYPE_UNSPECIFIED
}

func (x *IngestLogBatch) GetCompressedJsonl() []byte {
	if x != nil {
		return x.CompressedJsonl
	}
	return nil
}

func (x *IngestLogBatch) GetFlushAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FlushAt
	}
	return nil
}

type IngestLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *IngestLogBatch        `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogRequest) Reset() {
	*x = IngestLogRequest{}
	mi := &file_cicd_sensor_manager_v1_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogRequest) ProtoMessage() {}

func (x *IngestLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogRequest.ProtoReflect.Descriptor instead.
func (*IngestLogRequest) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_collector_proto_rawDescGZIP(), []int{1}
}

func (x *IngestLogRequest) GetBatch() *IngestLogBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

// IngestLogResponse confirms that the manager accepted and wrote one batch.
type IngestLogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// received_batches is always 1 for unary Phase 2a ingest.
	ReceivedBatches uint64 `protobuf:"varint,1,opt,name=received_batches,json=receivedBatches,proto3" json:"received_batches,omitempty"`
	BytesWritten    uint64 `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestLogResponse) Reset() {
	*x = IngestLogResponse{}
	mi := &file_cicd_sensor_manager_v1_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogResponse) ProtoMessage() {}

func (x *IngestLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogResponse.ProtoReflect.Descriptor instead.
func (*IngestLogResponse) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_collector_proto_rawDescGZIP(), []int{2}
}

func (x *IngestLogResponse) GetReceivedBatches() uint64 {
	if x != nil {
		return x.ReceivedBatches
	}
	return 0
}

func (x *IngestLogResponse) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

var File_cicd_sensor_manager_v1_collector_proto protoreflect.FileDescriptor

const file_cicd_sensor_manager_v1_collector_proto_rawDesc = "" +
	"\n" +
	"&cicd_sensor/manager/v1/collector.proto\x12\x16cicd_sensor.manager.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"cicd_sensor/manager/v1/types.proto\"\xab\x02\n" +
	"\x0eIngestLogBatch\x12F\n" +
	"\fjob_identity\x18\x01 \x01(\v2#.cicd_sensor.manager.v1.JobIdentityR\vjobIdentity\x123\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x1d.cicd_sensor.manager.v1.ScopeR\x05scope\x12:\n" +
	"\blog_type\x18\x03 \x01(\x0e2\x1f.cicd_sensor.manager.v1.LogTypeR\alogType\x12)\n" +
	"\x10compressed_jsonl\x18\x04 \x01(\fR\x0fcompressedJsonl\x125\n" +
	"\bflush_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aflushAt\"P\n" +
	"\x10IngestLogRequest\x12<\n" +
	"\x05batch\x18\x01 \x01(\v2&.cicd_sensor.manager.v1.IngestLogBatchR\x05batch\"c\n" +
	"\x11IngestLogResponse\x12)\n" +
	"\x10received_batches\x18\x01 \x01(\x04R\x0freceivedBatches\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x04R\fbytesWritten*m\n" +
	"\aLogType\x12\x18\n" +
	"\x14LOG_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12LOG_TYPE_DETECTION\x10\x01\x12\x1a\n" +
	"\x16LOG_TYPE_RUNTIME_EVENT\x10\x02\x12\x14\n" +
	"\x10LOG_TYPE_SUMMARY\x10\x03*A\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SCOPE_HOST\x10\x01\x12\x11\n" +
	"\rSCOPE_PROJECT\x10\x022t\n" +
	"\x10CollectorService\x12`\n" +
	"\tIngestLog\x12(.cicd_sensor.manager.v1.IngestLogRequest\x1a).cicd_sensor.manager.v1.IngestLogResponseB\xf6\x01\n" +
	"\x1acom.cicd_sensor.manager.v1B\x0eCollectorProtoP\x01ZRgithub.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/manager/v1;managerv1\xa2\x02\x03CMX\xaa\x02\x15CicdSensor.Manager.V1\xca\x02\x15CicdSensor\\Manager\\V1\xe2\x02!CicdSensor\\Manager\\V1\\GPBMetadata\xea\x02\x17CicdSensor::Manager::V1b\x06proto3"

var (
	file_cicd_sensor_manager_v1_collector_proto_rawDescOnce sync.Once
	file_cicd_sensor_manager_v1_collector_proto_rawDescData []byte
)

func file_cicd_sensor_manager_v1_collector_proto_rawDescGZIP() []byte {
	file_cicd_sensor_manager_v1_collector_proto_rawDescOnce.Do(func() {
		file_cicd_sensor_manager_v1_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cicd_sensor_manager_v1_collector_proto_rawDesc), len(file_cicd_sensor_manager_v1_collector_proto_rawDesc)))
	})
	return file_cicd_sensor_manager_v1_collector_proto_rawDescData
}

var file_cicd_sensor_manager_v1_collector_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cicd_sensor_manager_v1_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cicd_sensor_manager_v1_collector_proto_goTypes = []any{
	(LogType)(0),                  // 0: cicd_sensor.manager.v1.LogType
	(Scope)(0),                    // 1: cicd_sensor.manager.v1.Scope
	(*IngestLogBatch)(nil),        // 2: cicd_sensor.manager.v1.IngestLogBatch
	(*IngestLogRequest)(nil),      // 3: cicd_sensor.manager.v1.IngestLogRequest
	(*IngestLogResponse)(nil),     // 4: cicd_sensor.manager.v1.IngestLogResponse
	(*JobIdentity)(nil),           // 5: cicd_sensor.manager.v1.JobIdentity
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_cicd_sensor_manager_v1_collector_proto_depIdxs = []int32{
	5, // 0: cicd_sensor.manager.v1.IngestLogBatch.job_identity:type_name -> cicd_sensor.manager.v1.JobIdentity
	1, // 1: cicd_sensor.manager.v1.IngestLogBatch.scope:type_name -> cicd_sensor.manager.v1.Scope
	0, // 2: cicd_sensor.manager.v1.IngestLogBatch.log_type:type_name -> cicd_sensor.manager.v1.LogType
	6, // 3: cicd_sensor.manager.v1.IngestLogBatch.flush_at:type_name -> google.protobuf.Timestamp
	2, // 4: cicd_sensor.manager.v1.IngestLogRequest.batch:type_name -> cicd_sensor.manager.v1.IngestLogBatch
	3, // 5: cicd_sensor.manager.v1.CollectorService.IngestLog:input_type -> cicd_sensor.manager.v1.IngestLogRequest
	4, // 6: cicd_sensor.manager.v1.CollectorService.IngestLog:output_type -> cicd_sensor.manager.v1.IngestLogResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cicd_sensor_manager_v1_collector_proto_init() }
func file_cicd_sensor_manager_v1_collector_proto_init() {
	if File_cicd_sensor_manager_v1_collector_proto != nil {
		return
	}
	file_cicd_sensor_manager_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cicd_sensor_manager_v1_collector_proto_rawDesc), len(file_cicd_sensor_manager_v1_collector_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cicd_sensor_manager_v1_collector_proto_goTypes,
		DependencyIndexes: file_cicd_sensor_manager_v1_collector_proto_depIdxs,
		EnumInfos:         file_cicd_sensor_manager_v1_collector_proto_enumTypes,
		MessageInfos:      file_cicd_sensor_manager_v1_collector_proto_msgTypes,
	}.Build()
	File_cicd_sensor_manager_v1_collector_proto = out.File
	file_cicd_sensor_manager_v1_collector_proto_goTypes = nil
	file_cicd_sensor_manager_v1_collector_proto_depIdxs = nil
}
