// ConfigService distributes rule/output config to host and project scopes.
// Manager is stateless: every call authenticates and returns a fresh bundle.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cicd_sensor/manager/v1/config.proto

package managerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestedOutputs indicates which logs the caller will upload,
// so the manager can tailor output policy for those types.
type RequestedOutputs struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SummaryLog      bool                   `protobuf:"varint,1,opt,name=summary_log,json=summaryLog,proto3" json:"summary_log,omitempty"`
	DetectionLog    bool                   `protobuf:"varint,2,opt,name=detection_log,json=detectionLog,proto3" json:"detection_log,omitempty"`
	RuntimeEventLog bool                   `protobuf:"varint,3,opt,name=runtime_event_log,json=runtimeEventLog,proto3" json:"runtime_event_log,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestedOutputs) Reset() {
	*x = RequestedOutputs{}
	mi := &file_cicd_sensor_manager_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestedOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedOutputs) ProtoMessage() {}

func (x *RequestedOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedOutputs.ProtoReflect.Descriptor instead.
func (*RequestedOutputs) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *RequestedOutputs) GetSummaryLog() bool {
	if x != nil {
		return x.SummaryLog
	}
	return false
}

func (x *RequestedOutputs) GetDetectionLog() bool {
	if x != nil {
		return x.DetectionLog
	}
	return false
}

func (x *RequestedOutputs) GetRuntimeEventLog() bool {
	if x != nil {
		return x.RuntimeEventLog
	}
	return false
}

// FetchConfigRequest is the FetchConfig input. Auth is carried in headers,
// not in the body.
type FetchConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RunnerType is the agent-process-wide runner type ("machine" for VM /
	// physical server, "kubernetes" for a Pod) that helps the manager route
	// the request.
	RunnerType       string            `protobuf:"bytes,1,opt,name=runner_type,json=runnerType,proto3" json:"runner_type,omitempty"`
	JobIdentity      *JobIdentity      `protobuf:"bytes,2,opt,name=job_identity,json=jobIdentity,proto3" json:"job_identity,omitempty"`
	RequestedOutputs *RequestedOutputs `protobuf:"bytes,3,opt,name=requested_outputs,json=requestedOutputs,proto3" json:"requested_outputs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FetchConfigRequest) Reset() {
	*x = FetchConfigRequest{}
	mi := &file_cicd_sensor_manager_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigRequest) ProtoMessage() {}

func (x *FetchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigRequest.ProtoReflect.Descriptor instead.
func (*FetchConfigRequest) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *FetchConfigRequest) GetRunnerType() string {
	if x != nil {
		return x.RunnerType
	}
	return ""
}

func (x *FetchConfigRequest) GetJobIdentity() *JobIdentity {
	if x != nil {
		return x.JobIdentity
	}
	return nil
}

func (x *FetchConfigRequest) GetRequestedOutputs() *RequestedOutputs {
	if x != nil {
		return x.RequestedOutputs
	}
	return nil
}

// ServedConfig is the non-rule config portion returned to the agent.
type ServedConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ConfigRevision          string                 `protobuf:"bytes,1,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	DefaultMaxAlertsPerRule int32                  `protobuf:"varint,2,opt,name=default_max_alerts_per_rule,json=defaultMaxAlertsPerRule,proto3" json:"default_max_alerts_per_rule,omitempty"`
	OutputSettings          *OutputSettings        `protobuf:"bytes,3,opt,name=output_settings,json=outputSettings,proto3" json:"output_settings,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ServedConfig) Reset() {
	*x = ServedConfig{}
	mi := &file_cicd_sensor_manager_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServedConfig) ProtoMessage() {}

func (x *ServedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServedConfig.ProtoReflect.Descriptor instead.
func (*ServedConfig) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServedConfig) GetConfigRevision() string {
	if x != nil {
		return x.ConfigRevision
	}
	return ""
}

func (x *ServedConfig) GetDefaultMaxAlertsPerRule() int32 {
	if x != nil {
		return x.DefaultMaxAlertsPerRule
	}
	return 0
}

func (x *ServedConfig) GetOutputSettings() *OutputSettings {
	if x != nil {
		return x.OutputSettings
	}
	return nil
}

// FetchConfigResponse is the FetchConfig output.
type FetchConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ServedConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	RuleSources   []*RuleSource          `protobuf:"bytes,2,rep,name=rule_sources,json=ruleSources,proto3" json:"rule_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchConfigResponse) Reset() {
	*x = FetchConfigResponse{}
	mi := &file_cicd_sensor_manager_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigResponse) ProtoMessage() {}

func (x *FetchConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigResponse.ProtoReflect.Descriptor instead.
func (*FetchConfigResponse) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *FetchConfigResponse) GetConfig() *ServedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *FetchConfigResponse) GetRuleSources() []*RuleSource {
	if x != nil {
		return x.RuleSources
	}
	return nil
}

var File_cicd_sensor_manager_v1_config_proto protoreflect.FileDescriptor

const file_cicd_sensor_manager_v1_config_proto_rawDesc = "" +
	"\n" +
	"#cicd_sensor/manager/v1/config.proto\x12\x16cicd_sensor.manager.v1\x1a\"cicd_sensor/manager/v1/types.proto\"\x84\x01\n" +
	"\x10RequestedOutputs\x12\x1f\n" +
	"\vsummary_log\x18\x01 \x01(\bR\n" +
	"summaryLog\x12#\n" +
	"\rdetection_log\x18\x02 \x01(\bR\fdetectionLog\x12*\n" +
	"\x11runtime_event_log\x18\x03 \x01(\bR\x0fruntimeEventLog\"\xd4\x01\n" +
	"\x12FetchConfigRequest\x12\x1f\n" +
	"\vrunner_type\x18\x01 \x01(\tR\n" +
	"runnerType\x12F\n" +
	"\fjob_identity\x18\x02 \x01(\v2#.cicd_sensor.manager.v1.JobIdentityR\vjobIdentity\x12U\n" +
	"\x11requested_outputs\x18\x03 \x01(\v2(.cicd_sensor.manager.v1.RequestedOutputsR\x10requestedOutputs\"\xc6\x01\n" +
	"\fServedConfig\x12'\n" +
	"\x0fconfig_revision\x18\x01 \x01(\tR\x0econfigRevision\x12<\n" +
	"\x1bdefault_max_alerts_per_rule\x18\x02 \x01(\x05R\x17defaultMaxAlertsPerRule\x12O\n" +
	"\x0foutput_settings\x18\x03 \x01(\v2&.cicd_sensor.manager.v1.OutputSettingsR\x0eoutputSettings\"\x9a\x01\n" +
	"\x13FetchConfigResponse\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.cicd_sensor.manager.v1.ServedConfigR\x06config\x12E\n" +
	"\frule_sources\x18\x02 \x03(\v2\".cicd_sensor.manager.v1.RuleSourceR\vruleSources2w\n" +
	"\rConfigService\x12f\n" +
	"\vFetchConfig\x12*.cicd_sensor.manager.v1.FetchConfigRequest\x1a+.cicd_sensor.manager.v1.FetchConfigResponseB\xf3\x01\n" +
	"\x1acom.cicd_sensor.manager.v1B\vConfigProtoP\x01ZRgithub.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/manager/v1;managerv1\xa2\x02\x03CMX\xaa\x02\x15CicdSensor.Manager.V1\xca\x02\x15CicdSensor\\Manager\\V1\xe2\x02!CicdSensor\\Manager\\V1\\GPBMetadata\xea\x02\x17CicdSensor::Manager::V1b\x06proto3"

var (
	file_cicd_sensor_manager_v1_config_proto_rawDescOnce sync.Once
	file_cicd_sensor_manager_v1_config_proto_rawDescData []byte
)

func file_cicd_sensor_manager_v1_config_proto_rawDescGZIP() []byte {
	file_cicd_sensor_manager_v1_config_proto_rawDescOnce.Do(func() {
		file_cicd_sensor_manager_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cicd_sensor_manager_v1_config_proto_rawDesc), len(file_cicd_sensor_manager_v1_config_proto_rawDesc)))
	})
	return file_cicd_sensor_manager_v1_config_proto_rawDescData
}

var file_cicd_sensor_manager_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cicd_sensor_manager_v1_config_proto_goTypes = []any{
	(*RequestedOutputs)(nil),    // 0: cicd_sensor.manager.v1.RequestedOutputs
	(*FetchConfigRequest)(nil),  // 1: cicd_sensor.manager.v1.FetchConfigRequest
	(*ServedConfig)(nil),        // 2: cicd_sensor.manager.v1.ServedConfig
	(*FetchConfigResponse)(nil), // 3: cicd_sensor.manager.v1.FetchConfigResponse
	(*JobIdentity)(nil),         // 4: cicd_sensor.manager.v1.JobIdentity
	(*OutputSettings)(nil),      // 5: cicd_sensor.manager.v1.OutputSettings
	(*RuleSource)(nil),          // 6: cicd_sensor.manager.v1.RuleSource
}
var file_cicd_sensor_manager_v1_config_proto_depIdxs = []int32{
	4, // 0: cicd_sensor.manager.v1.FetchConfigRequest.job_identity:type_name -> cicd_sensor.manager.v1.JobIdentity
	0, // 1: cicd_sensor.manager.v1.FetchConfigRequest.requested_outputs:type_name -> cicd_sensor.manager.v1.RequestedOutputs
	5, // 2: cicd_sensor.manager.v1.ServedConfig.output_settings:type_name -> cicd_sensor.manager.v1.OutputSettings
	2, // 3: cicd_sensor.manager.v1.FetchConfigResponse.config:type_name -> cicd_sensor.manager.v1.ServedConfig
	6, // 4: cicd_sensor.manager.v1.FetchConfigResponse.rule_sources:type_name -> cicd_sensor.manager.v1.RuleSource
	1, // 5: cicd_sensor.manager.v1.ConfigService.FetchConfig:input_type -> cicd_sensor.manager.v1.FetchConfigRequest
	3, // 6: cicd_sensor.manager.v1.ConfigService.FetchConfig:output_type -> cicd_sensor.manager.v1.FetchConfigResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cicd_sensor_manager_v1_config_proto_init() }
func file_cicd_sensor_manager_v1_config_proto_init() {
	if File_cicd_sensor_manager_v1_config_proto != nil {
		return
	}
	file_cicd_sensor_manager_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cicd_sensor_manager_v1_config_proto_rawDesc), len(file_cicd_sensor_manager_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cicd_sensor_manager_v1_config_proto_goTypes,
		DependencyIndexes: file_cicd_sensor_manager_v1_config_proto_depIdxs,
		MessageInfos:      file_cicd_sensor_manager_v1_config_proto_msgTypes,
	}.Build()
	File_cicd_sensor_manager_v1_config_proto = out.File
	file_cicd_sensor_manager_v1_config_proto_goTypes = nil
	file_cicd_sensor_manager_v1_config_proto_depIdxs = nil
}
