// Common types shared by manager wire services. Proto is the single schema
// source of truth for jobcontext.
//
// Rule-authoring types mirror internal/rule/schema.go for manager delivery.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cicd_sensor/manager/v1/types.proto

package managerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobIdentity is the canonical identity of a single job execution,
// shared between agent and manager. Mirrors jobcontext.JobIdentity.
type JobIdentity struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Provider     string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderHost string                 `protobuf:"bytes,2,opt,name=provider_host,json=providerHost,proto3" json:"provider_host,omitempty"`
	ProjectPath  string                 `protobuf:"bytes,3,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	// GitHub-specific fields. Required when provider = "github".
	GithubRunId            string `protobuf:"bytes,10,opt,name=github_run_id,json=githubRunId,proto3" json:"github_run_id,omitempty"`
	GithubJob              string `protobuf:"bytes,11,opt,name=github_job,json=githubJob,proto3" json:"github_job,omitempty"`
	GithubRunAttempt       string `protobuf:"bytes,12,opt,name=github_run_attempt,json=githubRunAttempt,proto3" json:"github_run_attempt,omitempty"`
	GithubRunnerTrackingId string `protobuf:"bytes,13,opt,name=github_runner_tracking_id,json=githubRunnerTrackingId,proto3" json:"github_runner_tracking_id,omitempty"`
	// GitLab-specific fields. Required when provider = "gitlab".
	GitlabJobId   string `protobuf:"bytes,20,opt,name=gitlab_job_id,json=gitlabJobId,proto3" json:"gitlab_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobIdentity) Reset() {
	*x = JobIdentity{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobIdentity) ProtoMessage() {}

func (x *JobIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobIdentity.ProtoReflect.Descriptor instead.
func (*JobIdentity) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *JobIdentity) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *JobIdentity) GetProviderHost() string {
	if x != nil {
		return x.ProviderHost
	}
	return ""
}

func (x *JobIdentity) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *JobIdentity) GetGithubRunId() string {
	if x != nil {
		return x.GithubRunId
	}
	return ""
}

func (x *JobIdentity) GetGithubJob() string {
	if x != nil {
		return x.GithubJob
	}
	return ""
}

func (x *JobIdentity) GetGithubRunAttempt() string {
	if x != nil {
		return x.GithubRunAttempt
	}
	return ""
}

func (x *JobIdentity) GetGithubRunnerTrackingId() string {
	if x != nil {
		return x.GithubRunnerTrackingId
	}
	return ""
}

func (x *JobIdentity) GetGitlabJobId() string {
	if x != nil {
		return x.GitlabJobId
	}
	return ""
}

// Proto map values cannot be repeated fields directly.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RuleTargetMatcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderHost  string                 `protobuf:"bytes,1,opt,name=provider_host,json=providerHost,proto3" json:"provider_host,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleTargetMatcher) Reset() {
	*x = RuleTargetMatcher{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleTargetMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleTargetMatcher) ProtoMessage() {}

func (x *RuleTargetMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleTargetMatcher.ProtoReflect.Descriptor instead.
func (*RuleTargetMatcher) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *RuleTargetMatcher) GetProviderHost() string {
	if x != nil {
		return x.ProviderHost
	}
	return ""
}

func (x *RuleTargetMatcher) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RuleTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []*RuleTargetMatcher   `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []*RuleTargetMatcher   `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleTarget) Reset() {
	*x = RuleTarget{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleTarget) ProtoMessage() {}

func (x *RuleTarget) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleTarget.ProtoReflect.Descriptor instead.
func (*RuleTarget) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *RuleTarget) GetInclude() []*RuleTargetMatcher {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *RuleTarget) GetExclude() []*RuleTargetMatcher {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	EventType     string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Target        *RuleTarget            `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Condition     string                 `protobuf:"bytes,7,opt,name=condition,proto3" json:"condition,omitempty"`
	Exceptions    string                 `protobuf:"bytes,8,opt,name=exceptions,proto3" json:"exceptions,omitempty"`
	MaxAlerts     int32                  `protobuf:"varint,9,opt,name=max_alerts,json=maxAlerts,proto3" json:"max_alerts,omitempty"`
	Action        string                 `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *Rule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Rule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Rule) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Rule) GetTarget() *RuleTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Rule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Rule) GetExceptions() string {
	if x != nil {
		return x.Exceptions
	}
	return ""
}

func (x *Rule) GetMaxAlerts() int32 {
	if x != nil {
		return x.MaxAlerts
	}
	return 0
}

func (x *Rule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Rule) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RuleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RulesetId     string                 `protobuf:"bytes,1,opt,name=ruleset_id,json=rulesetId,proto3" json:"ruleset_id,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Lists         map[string]*StringList `protobuf:"bytes,3,rep,name=lists,proto3" json:"lists,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Rules         []*Rule                `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSet) Reset() {
	*x = RuleSet{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSet) ProtoMessage() {}

func (x *RuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSet.ProtoReflect.Descriptor instead.
func (*RuleSet) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *RuleSet) GetRulesetId() string {
	if x != nil {
		return x.RulesetId
	}
	return ""
}

func (x *RuleSet) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *RuleSet) GetLists() map[string]*StringList {
	if x != nil {
		return x.Lists
	}
	return nil
}

func (x *RuleSet) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type RuleModifierTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RulesetId     string                 `protobuf:"bytes,1,opt,name=ruleset_id,json=rulesetId,proto3" json:"ruleset_id,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleModifierTarget) Reset() {
	*x = RuleModifierTarget{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleModifierTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleModifierTarget) ProtoMessage() {}

func (x *RuleModifierTarget) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleModifierTarget.ProtoReflect.Descriptor instead.
func (*RuleModifierTarget) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *RuleModifierTarget) GetRulesetId() string {
	if x != nil {
		return x.RulesetId
	}
	return ""
}

func (x *RuleModifierTarget) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type RuleModifier struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModifierId        string                 `protobuf:"bytes,1,opt,name=modifier_id,json=modifierId,proto3" json:"modifier_id,omitempty"`
	Revision          string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Targets           []*RuleModifierTarget  `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	OverrideAction    *string                `protobuf:"bytes,5,opt,name=override_action,json=overrideAction,proto3,oneof" json:"override_action,omitempty"`
	OverrideMaxAlerts *int32                 `protobuf:"varint,6,opt,name=override_max_alerts,json=overrideMaxAlerts,proto3,oneof" json:"override_max_alerts,omitempty"`
	AddExceptions     string                 `protobuf:"bytes,7,opt,name=add_exceptions,json=addExceptions,proto3" json:"add_exceptions,omitempty"`
	AddTargetExclude  []*RuleTargetMatcher   `protobuf:"bytes,8,rep,name=add_target_exclude,json=addTargetExclude,proto3" json:"add_target_exclude,omitempty"`
	Disable           *bool                  `protobuf:"varint,9,opt,name=disable,proto3,oneof" json:"disable,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuleModifier) Reset() {
	*x = RuleModifier{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleModifier) ProtoMessage() {}

func (x *RuleModifier) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleModifier.ProtoReflect.Descriptor instead.
func (*RuleModifier) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *RuleModifier) GetModifierId() string {
	if x != nil {
		return x.ModifierId
	}
	return ""
}

func (x *RuleModifier) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *RuleModifier) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleModifier) GetTargets() []*RuleModifierTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *RuleModifier) GetOverrideAction() string {
	if x != nil && x.OverrideAction != nil {
		return *x.OverrideAction
	}
	return ""
}

func (x *RuleModifier) GetOverrideMaxAlerts() int32 {
	if x != nil && x.OverrideMaxAlerts != nil {
		return *x.OverrideMaxAlerts
	}
	return 0
}

func (x *RuleModifier) GetAddExceptions() string {
	if x != nil {
		return x.AddExceptions
	}
	return ""
}

func (x *RuleModifier) GetAddTargetExclude() []*RuleTargetMatcher {
	if x != nil {
		return x.AddTargetExclude
	}
	return nil
}

func (x *RuleModifier) GetDisable() bool {
	if x != nil && x.Disable != nil {
		return *x.Disable
	}
	return false
}

type RuleSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleSets      []*RuleSet             `protobuf:"bytes,1,rep,name=rule_sets,json=ruleSets,proto3" json:"rule_sets,omitempty"`
	RuleModifiers []*RuleModifier        `protobuf:"bytes,2,rep,name=rule_modifiers,json=ruleModifiers,proto3" json:"rule_modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSource) Reset() {
	*x = RuleSource{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSource) ProtoMessage() {}

func (x *RuleSource) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSource.ProtoReflect.Descriptor instead.
func (*RuleSource) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *RuleSource) GetRuleSets() []*RuleSet {
	if x != nil {
		return x.RuleSets
	}
	return nil
}

func (x *RuleSource) GetRuleModifiers() []*RuleModifier {
	if x != nil {
		return x.RuleModifiers
	}
	return nil
}

// OutputSetting tells the agent whether to send one log type and when to
// flush buffered JSONL records.
type OutputSetting struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Flush when buffered JSONL bytes reach this threshold. Zero disables it.
	FlushThresholdBytes  uint32 `protobuf:"varint,2,opt,name=flush_threshold_bytes,json=flushThresholdBytes,proto3" json:"flush_threshold_bytes,omitempty"`
	FlushIntervalSeconds uint32 `protobuf:"varint,3,opt,name=flush_interval_seconds,json=flushIntervalSeconds,proto3" json:"flush_interval_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OutputSetting) Reset() {
	*x = OutputSetting{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSetting) ProtoMessage() {}

func (x *OutputSetting) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSetting.ProtoReflect.Descriptor instead.
func (*OutputSetting) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *OutputSetting) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OutputSetting) GetFlushThresholdBytes() uint32 {
	if x != nil {
		return x.FlushThresholdBytes
	}
	return 0
}

func (x *OutputSetting) GetFlushIntervalSeconds() uint32 {
	if x != nil {
		return x.FlushIntervalSeconds
	}
	return 0
}

// OutputSettings tells the agent which logs should be sent to manager.
type OutputSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DetectionLog    *OutputSetting         `protobuf:"bytes,1,opt,name=detection_log,json=detectionLog,proto3" json:"detection_log,omitempty"`
	RuntimeEventLog *OutputSetting         `protobuf:"bytes,2,opt,name=runtime_event_log,json=runtimeEventLog,proto3" json:"runtime_event_log,omitempty"`
	SummaryLog      *OutputSetting         `protobuf:"bytes,3,opt,name=summary_log,json=summaryLog,proto3" json:"summary_log,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OutputSettings) Reset() {
	*x = OutputSettings{}
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSettings) ProtoMessage() {}

func (x *OutputSettings) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSettings.ProtoReflect.Descriptor instead.
func (*OutputSettings) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *OutputSettings) GetDetectionLog() *OutputSetting {
	if x != nil {
		return x.DetectionLog
	}
	return nil
}

func (x *OutputSettings) GetRuntimeEventLog() *OutputSetting {
	if x != nil {
		return x.RuntimeEventLog
	}
	return nil
}

func (x *OutputSettings) GetSummaryLog() *OutputSetting {
	if x != nil {
		return x.SummaryLog
	}
	return nil
}

var File_cicd_sensor_manager_v1_types_proto protoreflect.FileDescriptor

const file_cicd_sensor_manager_v1_types_proto_rawDesc = "" +
	"\n" +
	"\"cicd_sensor/manager/v1/types.proto\x12\x16cicd_sensor.manager.v1\x1a\x1bbuf/validate/validate.proto\"\xd8\x02\n" +
	"\vJobIdentity\x121\n" +
	"\bprovider\x18\x01 \x01(\tB\x15\xbaH\x12r\x10R\x06githubR\x06gitlabR\bprovider\x12#\n" +
	"\rprovider_host\x18\x02 \x01(\tR\fproviderHost\x12!\n" +
	"\fproject_path\x18\x03 \x01(\tR\vprojectPath\x12\"\n" +
	"\rgithub_run_id\x18\n" +
	" \x01(\tR\vgithubRunId\x12\x1d\n" +
	"\n" +
	"github_job\x18\v \x01(\tR\tgithubJob\x12,\n" +
	"\x12github_run_attempt\x18\f \x01(\tR\x10githubRunAttempt\x129\n" +
	"\x19github_runner_tracking_id\x18\r \x01(\tR\x16githubRunnerTrackingId\x12\"\n" +
	"\rgitlab_job_id\x18\x14 \x01(\tR\vgitlabJobId\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"L\n" +
	"\x11RuleTargetMatcher\x12#\n" +
	"\rprovider_host\x18\x01 \x01(\tR\fproviderHost\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x96\x01\n" +
	"\n" +
	"RuleTarget\x12C\n" +
	"\ainclude\x18\x01 \x03(\v2).cicd_sensor.manager.v1.RuleTargetMatcherR\ainclude\x12C\n" +
	"\aexclude\x18\x02 \x03(\v2).cicd_sensor.manager.v1.RuleTargetMatcherR\aexclude\"\xb7\x03\n" +
	"\x04Rule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12:\n" +
	"\x06target\x18\x06 \x01(\v2\".cicd_sensor.manager.v1.RuleTargetR\x06target\x12\x1c\n" +
	"\tcondition\x18\a \x01(\tR\tcondition\x12\x1e\n" +
	"\n" +
	"exceptions\x18\b \x01(\tR\n" +
	"exceptions\x12\x1d\n" +
	"\n" +
	"max_alerts\x18\t \x01(\x05R\tmaxAlerts\x12\x16\n" +
	"\x06action\x18\n" +
	" \x01(\tR\x06action\x12:\n" +
	"\x04tags\x18\v \x03(\v2&.cicd_sensor.manager.v1.Rule.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"\aRuleSet\x12\x1d\n" +
	"\n" +
	"ruleset_id\x18\x01 \x01(\tR\trulesetId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12@\n" +
	"\x05lists\x18\x03 \x03(\v2*.cicd_sensor.manager.v1.RuleSet.ListsEntryR\x05lists\x122\n" +
	"\x05rules\x18\x04 \x03(\v2\x1c.cicd_sensor.manager.v1.RuleR\x05rules\x1a\\\n" +
	"\n" +
	"ListsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".cicd_sensor.manager.v1.StringListR\x05value:\x028\x01\"L\n" +
	"\x12RuleModifierTarget\x12\x1d\n" +
	"\n" +
	"ruleset_id\x18\x01 \x01(\tR\trulesetId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\"\xed\x03\n" +
	"\fRuleModifier\x12\x1f\n" +
	"\vmodifier_id\x18\x01 \x01(\tR\n" +
	"modifierId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12D\n" +
	"\atargets\x18\x04 \x03(\v2*.cicd_sensor.manager.v1.RuleModifierTargetR\atargets\x12,\n" +
	"\x0foverride_action\x18\x05 \x01(\tH\x00R\x0eoverrideAction\x88\x01\x01\x123\n" +
	"\x13override_max_alerts\x18\x06 \x01(\x05H\x01R\x11overrideMaxAlerts\x88\x01\x01\x12%\n" +
	"\x0eadd_exceptions\x18\a \x01(\tR\raddExceptions\x12W\n" +
	"\x12add_target_exclude\x18\b \x03(\v2).cicd_sensor.manager.v1.RuleTargetMatcherR\x10addTargetExclude\x12\x1d\n" +
	"\adisable\x18\t \x01(\bH\x02R\adisable\x88\x01\x01B\x12\n" +
	"\x10_override_actionB\x16\n" +
	"\x14_override_max_alertsB\n" +
	"\n" +
	"\b_disable\"\x97\x01\n" +
	"\n" +
	"RuleSource\x12<\n" +
	"\trule_sets\x18\x01 \x03(\v2\x1f.cicd_sensor.manager.v1.RuleSetR\bruleSets\x12K\n" +
	"\x0erule_modifiers\x18\x02 \x03(\v2$.cicd_sensor.manager.v1.RuleModifierR\rruleModifiers\"\x93\x01\n" +
	"\rOutputSetting\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x122\n" +
	"\x15flush_threshold_bytes\x18\x02 \x01(\rR\x13flushThresholdBytes\x124\n" +
	"\x16flush_interval_seconds\x18\x03 \x01(\rR\x14flushIntervalSeconds\"\xf7\x01\n" +
	"\x0eOutputSettings\x12J\n" +
	"\rdetection_log\x18\x01 \x01(\v2%.cicd_sensor.manager.v1.OutputSettingR\fdetectionLog\x12Q\n" +
	"\x11runtime_event_log\x18\x02 \x01(\v2%.cicd_sensor.manager.v1.OutputSettingR\x0fruntimeEventLog\x12F\n" +
	"\vsummary_log\x18\x03 \x01(\v2%.cicd_sensor.manager.v1.OutputSettingR\n" +
	"summaryLogB\xf2\x01\n" +
	"\x1acom.cicd_sensor.manager.v1B\n" +
	"TypesProtoP\x01ZRgithub.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/manager/v1;managerv1\xa2\x02\x03CMX\xaa\x02\x15CicdSensor.Manager.V1\xca\x02\x15CicdSensor\\Manager\\V1\xe2\x02!CicdSensor\\Manager\\V1\\GPBMetadata\xea\x02\x17CicdSensor::Manager::V1b\x06proto3"

var (
	file_cicd_sensor_manager_v1_types_proto_rawDescOnce sync.Once
	file_cicd_sensor_manager_v1_types_proto_rawDescData []byte
)

func file_cicd_sensor_manager_v1_types_proto_rawDescGZIP() []byte {
	file_cicd_sensor_manager_v1_types_proto_rawDescOnce.Do(func() {
		file_cicd_sensor_manager_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cicd_sensor_manager_v1_types_proto_rawDesc), len(file_cicd_sensor_manager_v1_types_proto_rawDesc)))
	})
	return file_cicd_sensor_manager_v1_types_proto_rawDescData
}

var file_cicd_sensor_manager_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cicd_sensor_manager_v1_types_proto_goTypes = []any{
	(*JobIdentity)(nil),        // 0: cicd_sensor.manager.v1.JobIdentity
	(*StringList)(nil),         // 1: cicd_sensor.manager.v1.StringList
	(*RuleTargetMatcher)(nil),  // 2: cicd_sensor.manager.v1.RuleTargetMatcher
	(*RuleTarget)(nil),         // 3: cicd_sensor.manager.v1.RuleTarget
	(*Rule)(nil),               // 4: cicd_sensor.manager.v1.Rule
	(*RuleSet)(nil),            // 5: cicd_sensor.manager.v1.RuleSet
	(*RuleModifierTarget)(nil), // 6: cicd_sensor.manager.v1.RuleModifierTarget
	(*RuleModifier)(nil),       // 7: cicd_sensor.manager.v1.RuleModifier
	(*RuleSource)(nil),         // 8: cicd_sensor.manager.v1.RuleSource
	(*OutputSetting)(nil),      // 9: cicd_sensor.manager.v1.OutputSetting
	(*OutputSettings)(nil),     // 10: cicd_sensor.manager.v1.OutputSettings
	nil,                        // 11: cicd_sensor.manager.v1.Rule.TagsEntry
	nil,                        // 12: cicd_sensor.manager.v1.RuleSet.ListsEntry
}
var file_cicd_sensor_manager_v1_types_proto_depIdxs = []int32{
	2,  // 0: cicd_sensor.manager.v1.RuleTarget.include:type_name -> cicd_sensor.manager.v1.RuleTargetMatcher
	2,  // 1: cicd_sensor.manager.v1.RuleTarget.exclude:type_name -> cicd_sensor.manager.v1.RuleTargetMatcher
	3,  // 2: cicd_sensor.manager.v1.Rule.target:type_name -> cicd_sensor.manager.v1.RuleTarget
	11, // 3: cicd_sensor.manager.v1.Rule.tags:type_name -> cicd_sensor.manager.v1.Rule.TagsEntry
	12, // 4: cicd_sensor.manager.v1.RuleSet.lists:type_name -> cicd_sensor.manager.v1.RuleSet.ListsEntry
	4,  // 5: cicd_sensor.manager.v1.RuleSet.rules:type_name -> cicd_sensor.manager.v1.Rule
	6,  // 6: cicd_sensor.manager.v1.RuleModifier.targets:type_name -> cicd_sensor.manager.v1.RuleModifierTarget
	2,  // 7: cicd_sensor.manager.v1.RuleModifier.add_target_exclude:type_name -> cicd_sensor.manager.v1.RuleTargetMatcher
	5,  // 8: cicd_sensor.manager.v1.RuleSource.rule_sets:type_name -> cicd_sensor.manager.v1.RuleSet
	7,  // 9: cicd_sensor.manager.v1.RuleSource.rule_modifiers:type_name -> cicd_sensor.manager.v1.RuleModifier
	9,  // 10: cicd_sensor.manager.v1.OutputSettings.detection_log:type_name -> cicd_sensor.manager.v1.OutputSetting
	9,  // 11: cicd_sensor.manager.v1.OutputSettings.runtime_event_log:type_name -> cicd_sensor.manager.v1.OutputSetting
	9,  // 12: cicd_sensor.manager.v1.OutputSettings.summary_log:type_name -> cicd_sensor.manager.v1.OutputSetting
	1,  // 13: cicd_sensor.manager.v1.RuleSet.ListsEntry.value:type_name -> cicd_sensor.manager.v1.StringList
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cicd_sensor_manager_v1_types_proto_init() }
func file_cicd_sensor_manager_v1_types_proto_init() {
	if File_cicd_sensor_manager_v1_types_proto != nil {
		return
	}
	file_cicd_sensor_manager_v1_types_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cicd_sensor_manager_v1_types_proto_rawDesc), len(file_cicd_sensor_manager_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cicd_sensor_manager_v1_types_proto_goTypes,
		DependencyIndexes: file_cicd_sensor_manager_v1_types_proto_depIdxs,
		MessageInfos:      file_cicd_sensor_manager_v1_types_proto_msgTypes,
	}.Build()
	File_cicd_sensor_manager_v1_types_proto = out.File
	file_cicd_sensor_manager_v1_types_proto_goTypes = nil
	file_cicd_sensor_manager_v1_types_proto_depIdxs = nil
}
