// ConfigService distributes rule/output config to host and project scopes.
// Manager is stateless: every call authenticates and returns a fresh bundle.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cicd_sensor/manager/v1beta1/config.proto

package managerv1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestedOutputs indicates which logs the caller will upload,
// so the manager can tailor output policy for those types.
type RequestedOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       bool                   `protobuf:"varint,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Detection     bool                   `protobuf:"varint,2,opt,name=detection,proto3" json:"detection,omitempty"`
	RuntimeEvent  bool                   `protobuf:"varint,3,opt,name=runtime_event,json=runtimeEvent,proto3" json:"runtime_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestedOutputs) Reset() {
	*x = RequestedOutputs{}
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestedOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedOutputs) ProtoMessage() {}

func (x *RequestedOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedOutputs.ProtoReflect.Descriptor instead.
func (*RequestedOutputs) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1beta1_config_proto_rawDescGZIP(), []int{0}
}

func (x *RequestedOutputs) GetSummary() bool {
	if x != nil {
		return x.Summary
	}
	return false
}

func (x *RequestedOutputs) GetDetection() bool {
	if x != nil {
		return x.Detection
	}
	return false
}

func (x *RequestedOutputs) GetRuntimeEvent() bool {
	if x != nil {
		return x.RuntimeEvent
	}
	return false
}

// ARCScaleSet identifies one Actions Runner Controller
// `gha-runner-scale-set` release. It mirrors the two labels the ARC
// controller writes onto every runner pod
// (actions.github.com/scale-set-namespace and
// actions.github.com/scale-set-name) and lets the manager return
// per-scale-set host scope config so different scale-sets on the same
// cluster can carry different rules and outputs.
//
// Empty (zero) ARCScaleSet means single-scale-set: every job on the agent
// shares one host scope configuration. Non-ARC runner environments always
// send the zero value.
type ARCScaleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ARCScaleSet) Reset() {
	*x = ARCScaleSet{}
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARCScaleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARCScaleSet) ProtoMessage() {}

func (x *ARCScaleSet) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARCScaleSet.ProtoReflect.Descriptor instead.
func (*ARCScaleSet) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1beta1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ARCScaleSet) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ARCScaleSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// FetchConfigRequest is the FetchConfig input. Auth is carried in headers,
// not in the body.
type FetchConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RunnerType is the agent-process-wide runner type ("machine" for VM /
	// physical server, "kubernetes" for a Pod) that helps the manager route
	// the request.
	RunnerType       string            `protobuf:"bytes,1,opt,name=runner_type,json=runnerType,proto3" json:"runner_type,omitempty"`
	JobIdentity      *JobIdentity      `protobuf:"bytes,2,opt,name=job_identity,json=jobIdentity,proto3" json:"job_identity,omitempty"`
	RequestedOutputs *RequestedOutputs `protobuf:"bytes,3,opt,name=requested_outputs,json=requestedOutputs,proto3" json:"requested_outputs,omitempty"`
	// ARC scale-set identity for per-scale-set host scope isolation.
	// Optional; the zero value selects single-scale-set config.
	ArcScaleSet   *ARCScaleSet `protobuf:"bytes,4,opt,name=arc_scale_set,json=arcScaleSet,proto3" json:"arc_scale_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchConfigRequest) Reset() {
	*x = FetchConfigRequest{}
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigRequest) ProtoMessage() {}

func (x *FetchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigRequest.ProtoReflect.Descriptor instead.
func (*FetchConfigRequest) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1beta1_config_proto_rawDescGZIP(), []int{2}
}

func (x *FetchConfigRequest) GetRunnerType() string {
	if x != nil {
		return x.RunnerType
	}
	return ""
}

func (x *FetchConfigRequest) GetJobIdentity() *JobIdentity {
	if x != nil {
		return x.JobIdentity
	}
	return nil
}

func (x *FetchConfigRequest) GetRequestedOutputs() *RequestedOutputs {
	if x != nil {
		return x.RequestedOutputs
	}
	return nil
}

func (x *FetchConfigRequest) GetArcScaleSet() *ARCScaleSet {
	if x != nil {
		return x.ArcScaleSet
	}
	return nil
}

// ServedConfig is the non-rule config portion returned to the agent.
type ServedConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ConfigRevision          string                 `protobuf:"bytes,1,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	DefaultMaxAlertsPerRule int32                  `protobuf:"varint,2,opt,name=default_max_alerts_per_rule,json=defaultMaxAlertsPerRule,proto3" json:"default_max_alerts_per_rule,omitempty"`
	OutputSettings          *OutputSettings        `protobuf:"bytes,3,opt,name=output_settings,json=outputSettings,proto3" json:"output_settings,omitempty"`
	MonitorMode             bool                   `protobuf:"varint,4,opt,name=monitor_mode,json=monitorMode,proto3" json:"monitor_mode,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ServedConfig) Reset() {
	*x = ServedConfig{}
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServedConfig) ProtoMessage() {}

func (x *ServedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServedConfig.ProtoReflect.Descriptor instead.
func (*ServedConfig) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1beta1_config_proto_rawDescGZIP(), []int{3}
}

func (x *ServedConfig) GetConfigRevision() string {
	if x != nil {
		return x.ConfigRevision
	}
	return ""
}

func (x *ServedConfig) GetDefaultMaxAlertsPerRule() int32 {
	if x != nil {
		return x.DefaultMaxAlertsPerRule
	}
	return 0
}

func (x *ServedConfig) GetOutputSettings() *OutputSettings {
	if x != nil {
		return x.OutputSettings
	}
	return nil
}

func (x *ServedConfig) GetMonitorMode() bool {
	if x != nil {
		return x.MonitorMode
	}
	return false
}

// FetchConfigResponse is the FetchConfig output.
type FetchConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ServedConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	RuleSources   []*RuleSource          `protobuf:"bytes,2,rep,name=rule_sources,json=ruleSources,proto3" json:"rule_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchConfigResponse) Reset() {
	*x = FetchConfigResponse{}
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigResponse) ProtoMessage() {}

func (x *FetchConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_manager_v1beta1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigResponse.ProtoReflect.Descriptor instead.
func (*FetchConfigResponse) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_manager_v1beta1_config_proto_rawDescGZIP(), []int{4}
}

func (x *FetchConfigResponse) GetConfig() *ServedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *FetchConfigResponse) GetRuleSources() []*RuleSource {
	if x != nil {
		return x.RuleSources
	}
	return nil
}

var File_cicd_sensor_manager_v1beta1_config_proto protoreflect.FileDescriptor

const file_cicd_sensor_manager_v1beta1_config_proto_rawDesc = "" +
	"\n" +
	"(cicd_sensor/manager/v1beta1/config.proto\x12\x1bcicd_sensor.manager.v1beta1\x1a'cicd_sensor/manager/v1beta1/types.proto\"o\n" +
	"\x10RequestedOutputs\x12\x18\n" +
	"\asummary\x18\x01 \x01(\bR\asummary\x12\x1c\n" +
	"\tdetection\x18\x02 \x01(\bR\tdetection\x12#\n" +
	"\rruntime_event\x18\x03 \x01(\bR\fruntimeEvent\"?\n" +
	"\vARCScaleSet\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xac\x02\n" +
	"\x12FetchConfigRequest\x12\x1f\n" +
	"\vrunner_type\x18\x01 \x01(\tR\n" +
	"runnerType\x12K\n" +
	"\fjob_identity\x18\x02 \x01(\v2(.cicd_sensor.manager.v1beta1.JobIdentityR\vjobIdentity\x12Z\n" +
	"\x11requested_outputs\x18\x03 \x01(\v2-.cicd_sensor.manager.v1beta1.RequestedOutputsR\x10requestedOutputs\x12L\n" +
	"\rarc_scale_set\x18\x04 \x01(\v2(.cicd_sensor.manager.v1beta1.ARCScaleSetR\varcScaleSet\"\xee\x01\n" +
	"\fServedConfig\x12'\n" +
	"\x0fconfig_revision\x18\x01 \x01(\tR\x0econfigRevision\x12<\n" +
	"\x1bdefault_max_alerts_per_rule\x18\x02 \x01(\x05R\x17defaultMaxAlertsPerRule\x12T\n" +
	"\x0foutput_settings\x18\x03 \x01(\v2+.cicd_sensor.manager.v1beta1.OutputSettingsR\x0eoutputSettings\x12!\n" +
	"\fmonitor_mode\x18\x04 \x01(\bR\vmonitorMode\"\xa4\x01\n" +
	"\x13FetchConfigResponse\x12A\n" +
	"\x06config\x18\x01 \x01(\v2).cicd_sensor.manager.v1beta1.ServedConfigR\x06config\x12J\n" +
	"\frule_sources\x18\x02 \x03(\v2'.cicd_sensor.manager.v1beta1.RuleSourceR\vruleSources2\x81\x01\n" +
	"\rConfigService\x12p\n" +
	"\vFetchConfig\x12/.cicd_sensor.manager.v1beta1.FetchConfigRequest\x1a0.cicd_sensor.manager.v1beta1.FetchConfigResponseB\x96\x02\n" +
	"\x1fcom.cicd_sensor.manager.v1beta1B\vConfigProtoP\x01Z\\github.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/manager/v1beta1;managerv1beta1\xa2\x02\x03CMX\xaa\x02\x1aCicdSensor.Manager.V1beta1\xca\x02\x1aCicdSensor\\Manager\\V1beta1\xe2\x02&CicdSensor\\Manager\\V1beta1\\GPBMetadata\xea\x02\x1cCicdSensor::Manager::V1beta1b\x06proto3"

var (
	file_cicd_sensor_manager_v1beta1_config_proto_rawDescOnce sync.Once
	file_cicd_sensor_manager_v1beta1_config_proto_rawDescData []byte
)

func file_cicd_sensor_manager_v1beta1_config_proto_rawDescGZIP() []byte {
	file_cicd_sensor_manager_v1beta1_config_proto_rawDescOnce.Do(func() {
		file_cicd_sensor_manager_v1beta1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cicd_sensor_manager_v1beta1_config_proto_rawDesc), len(file_cicd_sensor_manager_v1beta1_config_proto_rawDesc)))
	})
	return file_cicd_sensor_manager_v1beta1_config_proto_rawDescData
}

var file_cicd_sensor_manager_v1beta1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cicd_sensor_manager_v1beta1_config_proto_goTypes = []any{
	(*RequestedOutputs)(nil),    // 0: cicd_sensor.manager.v1beta1.RequestedOutputs
	(*ARCScaleSet)(nil),         // 1: cicd_sensor.manager.v1beta1.ARCScaleSet
	(*FetchConfigRequest)(nil),  // 2: cicd_sensor.manager.v1beta1.FetchConfigRequest
	(*ServedConfig)(nil),        // 3: cicd_sensor.manager.v1beta1.ServedConfig
	(*FetchConfigResponse)(nil), // 4: cicd_sensor.manager.v1beta1.FetchConfigResponse
	(*JobIdentity)(nil),         // 5: cicd_sensor.manager.v1beta1.JobIdentity
	(*OutputSettings)(nil),      // 6: cicd_sensor.manager.v1beta1.OutputSettings
	(*RuleSource)(nil),          // 7: cicd_sensor.manager.v1beta1.RuleSource
}
var file_cicd_sensor_manager_v1beta1_config_proto_depIdxs = []int32{
	5, // 0: cicd_sensor.manager.v1beta1.FetchConfigRequest.job_identity:type_name -> cicd_sensor.manager.v1beta1.JobIdentity
	0, // 1: cicd_sensor.manager.v1beta1.FetchConfigRequest.requested_outputs:type_name -> cicd_sensor.manager.v1beta1.RequestedOutputs
	1, // 2: cicd_sensor.manager.v1beta1.FetchConfigRequest.arc_scale_set:type_name -> cicd_sensor.manager.v1beta1.ARCScaleSet
	6, // 3: cicd_sensor.manager.v1beta1.ServedConfig.output_settings:type_name -> cicd_sensor.manager.v1beta1.OutputSettings
	3, // 4: cicd_sensor.manager.v1beta1.FetchConfigResponse.config:type_name -> cicd_sensor.manager.v1beta1.ServedConfig
	7, // 5: cicd_sensor.manager.v1beta1.FetchConfigResponse.rule_sources:type_name -> cicd_sensor.manager.v1beta1.RuleSource
	2, // 6: cicd_sensor.manager.v1beta1.ConfigService.FetchConfig:input_type -> cicd_sensor.manager.v1beta1.FetchConfigRequest
	4, // 7: cicd_sensor.manager.v1beta1.ConfigService.FetchConfig:output_type -> cicd_sensor.manager.v1beta1.FetchConfigResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cicd_sensor_manager_v1beta1_config_proto_init() }
func file_cicd_sensor_manager_v1beta1_config_proto_init() {
	if File_cicd_sensor_manager_v1beta1_config_proto != nil {
		return
	}
	file_cicd_sensor_manager_v1beta1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cicd_sensor_manager_v1beta1_config_proto_rawDesc), len(file_cicd_sensor_manager_v1beta1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cicd_sensor_manager_v1beta1_config_proto_goTypes,
		DependencyIndexes: file_cicd_sensor_manager_v1beta1_config_proto_depIdxs,
		MessageInfos:      file_cicd_sensor_manager_v1beta1_config_proto_msgTypes,
	}.Build()
	File_cicd_sensor_manager_v1beta1_config_proto = out.File
	file_cicd_sensor_manager_v1beta1_config_proto_goTypes = nil
	file_cicd_sensor_manager_v1beta1_config_proto_depIdxs = nil
}
