package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"html/template"
	"io"
	"net/url"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/cicd-sensor/cicd-sensor/internal/resultdoc"
)

const (
	stepSummaryHeaderDetected   = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-detected.svg"
	stepSummaryHeaderNoAlert    = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-no-alert.svg"
	stepSummaryHeaderTerminated = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-terminate.svg"

	stepSummaryTopN         = 5
	stepSummaryProcessLimit = 5
)

var stepSummaryTemplate = template.Must(template.New("stepsummary").Parse(`<hr />

{{if .HeaderLink}}<a href="{{.HeaderLink}}">{{end}}<img src="{{.HeaderURL}}" width="650" alt="cicd-sensor - {{.Verdict}}" />{{if .HeaderLink}}</a>{{end}}

{{if .HealthFailed}}Agent health check failed during the post step. Counts and rule hits are unavailable for this run.

{{end}}{{if .RuleHits}}### Top 5 rule matches

{{range .RuleHits}}- {{.Emoji}} <code>{{.RuleID}}</code>{{if $.HTMLURL}} — <a href="{{$.HTMLURL}}#hits">Details</a>{{end}} — **{{.Count}}**{{template "processes" .}}
{{end}}
{{end}}{{if .Domains}}### Top 5 domain observations

{{range .Domains}}- <code>{{.Domain}}</code>{{if $.HTMLURL}} — <a href="{{$.HTMLURL}}#domains">Details</a>{{end}} — **{{.Count}}**{{template "processes" .}}
{{end}}
{{end}}{{if .Networks}}### Top 5 network connections

{{range .Networks}}- <code>{{.Endpoint}}</code>{{if .Protocol}} <code>{{.Protocol}}</code>{{end}}{{if $.HTMLURL}} — <a href="{{$.HTMLURL}}#network">Details</a>{{end}} — **{{.Count}}**{{template "processes" .}}
{{end}}
{{end}}{{if .TimelineURL}}<br/>

📊 <a href="{{.TimelineURL}}">Or open the full timeline ({{.TotalEvents}} events) →</a>

<br/>

{{end}}{{if .DebugURL}}🧰 <a href="{{.DebugURL}}">Open the cicd-sensor debug bundle</a>

{{end}}<sub>Generated by <a href="https://github.com/cicd-sensor/cicd-sensor">cicd-sensor</a></sub>

<hr />
{{define "processes"}}{{if .Processes}} · {{range $i, $p := .Processes}}{{if $i}}, {{end}}<code>{{$p}}</code>{{end}}{{if .ProcessOverflow}}, +{{.ProcessOverflow}} more{{end}}{{end}}{{end}}`))

type reportStepSummaryOptions struct {
	htmlURL      string
	debugURL     string
	healthFailed bool
	help         bool
}

type stepSummaryView struct {
	Verdict      string
	HeaderURL    string
	HeaderLink   string
	HTMLURL      string
	DebugURL     string
	HealthFailed bool
	RuleHits     []stepSummaryRuleHit
	Domains      []stepSummaryDomain
	Networks     []stepSummaryNetwork
	TimelineURL  string
	TotalEvents  int
}

type stepSummaryProcessList struct {
	Processes       []string
	ProcessOverflow int
}

type stepSummaryRuleHit struct {
	stepSummaryProcessList
	RuleID string
	Emoji  string
	Count  int
}

type stepSummaryDomain struct {
	stepSummaryProcessList
	Domain string
	Count  int
}

type stepSummaryNetwork struct {
	stepSummaryProcessList
	Endpoint string
	Protocol string
	Count    int
}

// runReportStepSummary renders GitHub Step Summary Markdown for cicd-sensor-action.
func runReportStepSummary(_ context.Context, args []string, stdin io.Reader, stdout, stderr io.Writer) (int, error) {
	opts, err := parseReportStepSummaryArgs(args, stderr)
	if err != nil {
		return 2, err
	}
	if opts.help {
		return 0, nil
	}

	var input []byte
	if stdin != nil {
		input, err = readReportInput(stdin)
		if err != nil {
			return 1, fmt.Errorf("read input: %w", err)
		}
	}

	var summaryLog resultdoc.JobEventSummaryForReport
	if len(bytes.TrimSpace(input)) > 0 {
		if err := json.Unmarshal(input, &summaryLog); err != nil {
			return 1, fmt.Errorf("decode summary_log: %w", err)
		}
	}

	body, err := renderStepSummaryMarkdown(summaryLog, opts)
	if err != nil {
		return 1, err
	}
	if _, err := stdout.Write(body); err != nil {
		return 1, fmt.Errorf("write stdout: %w", err)
	}
	return 0, nil
}

func parseReportStepSummaryArgs(args []string, stderr io.Writer) (reportStepSummaryOptions, error) {
	var opts reportStepSummaryOptions
	fs := flag.NewFlagSet("report stepsummary", flag.ContinueOnError)
	fs.SetOutput(stderr)
	fs.Usage = func() {
		fmt.Fprintln(fs.Output(), "usage: cicd-sensorctl report stepsummary [flags]")
		fmt.Fprintln(fs.Output())
		fmt.Fprintln(fs.Output(), "Input:")
		fmt.Fprintln(fs.Output(), "  Reads summary_log JSON from stdin when available.")
		fmt.Fprintln(fs.Output())
		fmt.Fprintln(fs.Output(), "Optional:")
		fmt.Fprintln(fs.Output(), "  --html-url URL")
		fmt.Fprintln(fs.Output(), "        Trusted URL for the uploaded HTML report artifact.")
		fmt.Fprintln(fs.Output(), "  --debug-url URL")
		fmt.Fprintln(fs.Output(), "        Trusted URL for the uploaded debug artifact.")
		fmt.Fprintln(fs.Output(), "  --health-failed")
		fmt.Fprintln(fs.Output(), "        Render an agent health-failure summary.")
	}
	fs.StringVar(&opts.htmlURL, "html-url", "", "Trusted URL for the HTML report artifact.")
	fs.StringVar(&opts.debugURL, "debug-url", "", "Trusted URL for the debug artifact.")
	fs.BoolVar(&opts.healthFailed, "health-failed", false, "Render health-failure summary.")
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			opts.help = true
			return opts, nil
		}
		return opts, err
	}
	if fs.NArg() != 0 {
		return opts, newUsageError(2, "report stepsummary: too many arguments")
	}
	return opts, nil
}

func renderStepSummaryMarkdown(summaryLog resultdoc.JobEventSummaryForReport, opts reportStepSummaryOptions) ([]byte, error) {
	htmlURL, err := trustedStepSummaryURL(opts.htmlURL)
	if err != nil {
		return nil, fmt.Errorf("html-url: %w", err)
	}
	debugURL, err := trustedStepSummaryURL(opts.debugURL)
	if err != nil {
		return nil, fmt.Errorf("debug-url: %w", err)
	}

	verdict := resultdoc.ResultNoAlert
	if opts.healthFailed {
		verdict = "health_failed"
	} else {
		switch summaryLog.ResultSummary.Result {
		case resultdoc.ResultNoAlert, resultdoc.ResultDetected, resultdoc.ResultTerminated:
			verdict = summaryLog.ResultSummary.Result
		}
	}

	view := stepSummaryView{
		Verdict:      verdict,
		HeaderURL:    stepSummaryHeaderURL(verdict),
		HeaderLink:   htmlURL,
		HTMLURL:      htmlURL,
		DebugURL:     debugURL,
		HealthFailed: opts.healthFailed,
	}
	if !opts.healthFailed {
		view.RuleHits = topStepSummaryRuleHits(summaryLog.Hits, stepSummaryTopN)
		view.Domains = topStepSummaryDomains(summaryLog.DomainObservations, stepSummaryTopN)
		view.Networks = topStepSummaryNetworks(summaryLog.NetworkConnections, stepSummaryTopN)
		view.TotalEvents = len(summaryLog.Hits) + len(summaryLog.DomainObservations) + len(summaryLog.NetworkConnections)
		if htmlURL != "" && view.TotalEvents > 0 {
			view.TimelineURL = htmlURL + "#hits"
		}
	}

	var out bytes.Buffer
	if err := stepSummaryTemplate.Execute(&out, view); err != nil {
		return nil, fmt.Errorf("render step summary: %w", err)
	}
	return out.Bytes(), nil
}

func topStepSummaryRuleHits(hits []resultdoc.HitRecord, limit int) []stepSummaryRuleHit {
	type group struct {
		ruleID    string
		action    string
		count     int
		processes map[string]struct{}
	}
	groups := make(map[string]*group)
	for _, hit := range hits {
		ruleID := stepSummaryDisplayText(hit.RuleID, 64, "unknown")
		g := groups[ruleID]
		if g == nil {
			g = &group{ruleID: ruleID, processes: make(map[string]struct{})}
			groups[ruleID] = g
		}
		g.count++
		if stepSummaryActionRank(hit.Action) > stepSummaryActionRank(g.action) {
			g.action = hit.Action
		}
		if hit.Process != nil {
			addStepSummaryProcess(g.processes, hit.Process.ExecPath)
		}
	}

	minRank := stepSummaryActionRank("detect")
	ordered := make([]*group, 0, len(groups))
	for _, g := range groups {
		if stepSummaryActionRank(g.action) < minRank {
			continue
		}
		ordered = append(ordered, g)
	}
	sort.Slice(ordered, func(i, j int) bool {
		if ordered[i].count != ordered[j].count {
			return ordered[i].count > ordered[j].count
		}
		return ordered[i].ruleID < ordered[j].ruleID
	})

	out := make([]stepSummaryRuleHit, 0, min(limit, len(ordered)))
	for _, g := range ordered[:min(limit, len(ordered))] {
		out = append(out, stepSummaryRuleHit{
			RuleID:                 g.ruleID,
			Emoji:                  stepSummaryActionEmoji(g.action),
			Count:                  g.count,
			stepSummaryProcessList: stepSummaryProcesses(g.processes),
		})
	}
	return out
}

func topStepSummaryDomains(observations []resultdoc.DomainObservation, limit int) []stepSummaryDomain {
	type group struct {
		domain    string
		count     int
		processes map[string]struct{}
	}
	groups := make(map[string]*group)
	for _, observation := range observations {
		domain := stepSummaryDisplayText(observation.Domain, 96, "unknown")
		g := groups[domain]
		if g == nil {
			g = &group{domain: domain, processes: make(map[string]struct{})}
			groups[domain] = g
		}
		g.count += len(observation.Processes)
		for _, process := range observation.Processes {
			addStepSummaryProcess(g.processes, process.ExecPath)
		}
	}

	ordered := make([]*group, 0, len(groups))
	for _, g := range groups {
		ordered = append(ordered, g)
	}
	sort.Slice(ordered, func(i, j int) bool {
		if ordered[i].count != ordered[j].count {
			return ordered[i].count > ordered[j].count
		}
		return ordered[i].domain < ordered[j].domain
	})

	out := make([]stepSummaryDomain, 0, min(limit, len(ordered)))
	for _, g := range ordered[:min(limit, len(ordered))] {
		out = append(out, stepSummaryDomain{
			Domain:                 g.domain,
			Count:                  g.count,
			stepSummaryProcessList: stepSummaryProcesses(g.processes),
		})
	}
	return out
}

func topStepSummaryNetworks(connections []resultdoc.NetworkConnection, limit int) []stepSummaryNetwork {
	type group struct {
		endpoint  string
		protocol  string
		count     int
		processes map[string]struct{}
	}
	groups := make(map[string]*group)
	for _, connection := range connections {
		protocol := strings.ToUpper(stepSummaryDisplayText(connection.Protocol, 12, ""))
		endpoint := stepSummaryEndpoint(connection.RemoteIP, connection.RemotePort)
		key := endpoint + "\x00" + protocol
		g := groups[key]
		if g == nil {
			g = &group{endpoint: endpoint, protocol: protocol, processes: make(map[string]struct{})}
			groups[key] = g
		}
		g.count += len(connection.Processes)
		for _, process := range connection.Processes {
			addStepSummaryProcess(g.processes, process.ExecPath)
		}
	}

	ordered := make([]*group, 0, len(groups))
	for _, g := range groups {
		ordered = append(ordered, g)
	}
	sort.Slice(ordered, func(i, j int) bool {
		if ordered[i].count != ordered[j].count {
			return ordered[i].count > ordered[j].count
		}
		if ordered[i].endpoint != ordered[j].endpoint {
			return ordered[i].endpoint < ordered[j].endpoint
		}
		return ordered[i].protocol < ordered[j].protocol
	})

	out := make([]stepSummaryNetwork, 0, min(limit, len(ordered)))
	for _, g := range ordered[:min(limit, len(ordered))] {
		out = append(out, stepSummaryNetwork{
			Endpoint:               g.endpoint,
			Protocol:               g.protocol,
			Count:                  g.count,
			stepSummaryProcessList: stepSummaryProcesses(g.processes),
		})
	}
	return out
}

func stepSummaryProcesses(processes map[string]struct{}) stepSummaryProcessList {
	ordered := make([]string, 0, len(processes))
	for process := range processes {
		ordered = append(ordered, process)
	}
	sort.Strings(ordered)
	if len(ordered) <= stepSummaryProcessLimit {
		return stepSummaryProcessList{Processes: ordered}
	}
	return stepSummaryProcessList{
		Processes:       ordered[:stepSummaryProcessLimit],
		ProcessOverflow: len(ordered) - stepSummaryProcessLimit,
	}
}

func addStepSummaryProcess(processes map[string]struct{}, execPath string) {
	process := stepSummaryProcessName(execPath)
	if process == "" {
		return
	}
	processes[process] = struct{}{}
}

func stepSummaryProcessName(execPath string) string {
	execPath = strings.TrimSpace(execPath)
	if execPath == "" {
		return ""
	}
	idx := strings.LastIndexAny(execPath, `/\`)
	if idx >= 0 && idx+1 < len(execPath) {
		execPath = execPath[idx+1:]
	}
	return stepSummaryDisplayText(execPath, 48, "")
}

func stepSummaryEndpoint(remoteIP string, remotePort int64) string {
	ip := stepSummaryDisplayText(remoteIP, 80, "unknown")
	if remotePort <= 0 {
		return ip
	}
	if strings.Contains(ip, ":") && !strings.HasPrefix(ip, "[") {
		ip = "[" + ip + "]"
	}
	return ip + ":" + strconv.FormatInt(remotePort, 10)
}

func stepSummaryDisplayText(value string, maxRunes int, fallback string) string {
	value = strings.Map(func(r rune) rune {
		switch {
		case r < 0x20 || (r >= 0x7f && r <= 0x9f):
			return ' '
		case (r >= 0x202a && r <= 0x202e) || (r >= 0x2066 && r <= 0x2069):
			return -1
		default:
			return r
		}
	}, value)
	value = strings.Join(strings.Fields(value), " ")
	if value == "" {
		return fallback
	}
	if utf8.RuneCountInString(value) <= maxRunes {
		return value
	}
	runes := []rune(value)
	if maxRunes <= 3 {
		return string(runes[:maxRunes])
	}
	return string(runes[:maxRunes-3]) + "..."
}

func stepSummaryActionRank(action string) int {
	switch action {
	case "terminate":
		return 3
	case "detect", "alert":
		return 2
	case "collect":
		return 1
	default:
		return 0
	}
}

func stepSummaryActionEmoji(action string) string {
	switch action {
	case "terminate":
		return "🛑"
	case "collect":
		return "📋"
	default:
		return "⚠️"
	}
}

func stepSummaryHeaderURL(verdict string) string {
	switch verdict {
	case resultdoc.ResultDetected:
		return stepSummaryHeaderDetected
	case resultdoc.ResultTerminated, "health_failed":
		return stepSummaryHeaderTerminated
	default:
		return stepSummaryHeaderNoAlert
	}
}

func trustedStepSummaryURL(raw string) (string, error) {
	if raw == "" {
		return "", nil
	}
	u, err := url.Parse(raw)
	if err != nil {
		return "", err
	}
	if u.Scheme != "https" && u.Scheme != "http" {
		return "", fmt.Errorf("unsupported scheme %q", u.Scheme)
	}
	if u.Host == "" {
		return "", fmt.Errorf("missing host")
	}
	return u.String(), nil
}
