// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cicd_sensor/log/v1/common.proto

package logv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobLogContext struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Provider     string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderHost string                 `protobuf:"bytes,2,opt,name=provider_host,proto3" json:"provider_host,omitempty"`
	ProjectPath  string                 `protobuf:"bytes,3,opt,name=project_path,proto3" json:"project_path,omitempty"`
	RunnerKind   string                 `protobuf:"bytes,4,opt,name=runner_kind,proto3" json:"runner_kind,omitempty"`
	JobLink      string                 `protobuf:"bytes,5,opt,name=job_link,proto3" json:"job_link,omitempty"`
	CommitSha    string                 `protobuf:"bytes,6,opt,name=commit_sha,proto3" json:"commit_sha,omitempty"`
	RefName      string                 `protobuf:"bytes,7,opt,name=ref_name,proto3" json:"ref_name,omitempty"`
	Trigger      string                 `protobuf:"bytes,8,opt,name=trigger,proto3" json:"trigger,omitempty"`
	ActorId      string                 `protobuf:"bytes,9,opt,name=actor_id,proto3" json:"actor_id,omitempty"`
	ActorName    string                 `protobuf:"bytes,10,opt,name=actor_name,proto3" json:"actor_name,omitempty"`
	// GitHub only.
	GithubRunId            string `protobuf:"bytes,20,opt,name=github_run_id,proto3" json:"github_run_id,omitempty"`
	GithubJob              string `protobuf:"bytes,21,opt,name=github_job,proto3" json:"github_job,omitempty"`
	GithubRunAttempt       string `protobuf:"bytes,22,opt,name=github_run_attempt,proto3" json:"github_run_attempt,omitempty"`
	GithubRunnerTrackingId string `protobuf:"bytes,23,opt,name=github_runner_tracking_id,proto3" json:"github_runner_tracking_id,omitempty"`
	GithubWorkflowRef      string `protobuf:"bytes,24,opt,name=github_workflow_ref,proto3" json:"github_workflow_ref,omitempty"`
	GithubWorkflowSha      string `protobuf:"bytes,25,opt,name=github_workflow_sha,proto3" json:"github_workflow_sha,omitempty"`
	GithubWorkflow         string `protobuf:"bytes,26,opt,name=github_workflow,proto3" json:"github_workflow,omitempty"`
	// GitLab only.
	GitlabJobId        string `protobuf:"bytes,30,opt,name=gitlab_job_id,proto3" json:"gitlab_job_id,omitempty"`
	GitlabJobName      string `protobuf:"bytes,31,opt,name=gitlab_job_name,proto3" json:"gitlab_job_name,omitempty"`
	GitlabConfigRefUri string `protobuf:"bytes,32,opt,name=gitlab_config_ref_uri,proto3" json:"gitlab_config_ref_uri,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobLogContext) Reset() {
	*x = JobLogContext{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLogContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLogContext) ProtoMessage() {}

func (x *JobLogContext) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLogContext.ProtoReflect.Descriptor instead.
func (*JobLogContext) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *JobLogContext) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *JobLogContext) GetProviderHost() string {
	if x != nil {
		return x.ProviderHost
	}
	return ""
}

func (x *JobLogContext) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *JobLogContext) GetRunnerKind() string {
	if x != nil {
		return x.RunnerKind
	}
	return ""
}

func (x *JobLogContext) GetJobLink() string {
	if x != nil {
		return x.JobLink
	}
	return ""
}

func (x *JobLogContext) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *JobLogContext) GetRefName() string {
	if x != nil {
		return x.RefName
	}
	return ""
}

func (x *JobLogContext) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *JobLogContext) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *JobLogContext) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *JobLogContext) GetGithubRunId() string {
	if x != nil {
		return x.GithubRunId
	}
	return ""
}

func (x *JobLogContext) GetGithubJob() string {
	if x != nil {
		return x.GithubJob
	}
	return ""
}

func (x *JobLogContext) GetGithubRunAttempt() string {
	if x != nil {
		return x.GithubRunAttempt
	}
	return ""
}

func (x *JobLogContext) GetGithubRunnerTrackingId() string {
	if x != nil {
		return x.GithubRunnerTrackingId
	}
	return ""
}

func (x *JobLogContext) GetGithubWorkflowRef() string {
	if x != nil {
		return x.GithubWorkflowRef
	}
	return ""
}

func (x *JobLogContext) GetGithubWorkflowSha() string {
	if x != nil {
		return x.GithubWorkflowSha
	}
	return ""
}

func (x *JobLogContext) GetGithubWorkflow() string {
	if x != nil {
		return x.GithubWorkflow
	}
	return ""
}

func (x *JobLogContext) GetGitlabJobId() string {
	if x != nil {
		return x.GitlabJobId
	}
	return ""
}

func (x *JobLogContext) GetGitlabJobName() string {
	if x != nil {
		return x.GitlabJobName
	}
	return ""
}

func (x *JobLogContext) GetGitlabConfigRefUri() string {
	if x != nil {
		return x.GitlabConfigRefUri
	}
	return ""
}

type EventRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv7 shared by telemetry and detection rows derived from this event.
	Id                string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind              string                    `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Tags              []string                  `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Process           *ProcessSummary           `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	ProcessExec       *ProcessExecPayload       `protobuf:"bytes,10,opt,name=process_exec,proto3" json:"process_exec,omitempty"`
	NetworkConnect    *NetworkConnectPayload    `protobuf:"bytes,11,opt,name=network_connect,proto3" json:"network_connect,omitempty"`
	UnixSocketConnect *UnixSocketConnectPayload `protobuf:"bytes,12,opt,name=unix_socket_connect,proto3" json:"unix_socket_connect,omitempty"`
	FileOpen          *FileOpenPayload          `protobuf:"bytes,13,opt,name=file_open,proto3" json:"file_open,omitempty"`
	FileRemove        *FileRemovePayload        `protobuf:"bytes,14,opt,name=file_remove,proto3" json:"file_remove,omitempty"`
	FileMove          *FileMovePayload          `protobuf:"bytes,15,opt,name=file_move,proto3" json:"file_move,omitempty"`
	FileLink          *FileLinkPayload          `protobuf:"bytes,16,opt,name=file_link,proto3" json:"file_link,omitempty"`
	Domain            *DomainPayload            `protobuf:"bytes,18,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventRecord) Reset() {
	*x = EventRecord{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRecord) ProtoMessage() {}

func (x *EventRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRecord.ProtoReflect.Descriptor instead.
func (*EventRecord) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *EventRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventRecord) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EventRecord) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventRecord) GetProcess() *ProcessSummary {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *EventRecord) GetProcessExec() *ProcessExecPayload {
	if x != nil {
		return x.ProcessExec
	}
	return nil
}

func (x *EventRecord) GetNetworkConnect() *NetworkConnectPayload {
	if x != nil {
		return x.NetworkConnect
	}
	return nil
}

func (x *EventRecord) GetUnixSocketConnect() *UnixSocketConnectPayload {
	if x != nil {
		return x.UnixSocketConnect
	}
	return nil
}

func (x *EventRecord) GetFileOpen() *FileOpenPayload {
	if x != nil {
		return x.FileOpen
	}
	return nil
}

func (x *EventRecord) GetFileRemove() *FileRemovePayload {
	if x != nil {
		return x.FileRemove
	}
	return nil
}

func (x *EventRecord) GetFileMove() *FileMovePayload {
	if x != nil {
		return x.FileMove
	}
	return nil
}

func (x *EventRecord) GetFileLink() *FileLinkPayload {
	if x != nil {
		return x.FileLink
	}
	return nil
}

func (x *EventRecord) GetDomain() *DomainPayload {
	if x != nil {
		return x.Domain
	}
	return nil
}

type ProcessSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ExecPath      string                 `protobuf:"bytes,2,opt,name=exec_path,proto3" json:"exec_path,omitempty"`
	Argv          []string               `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	Ancestors     []*AncestorProcess     `protobuf:"bytes,4,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessSummary) Reset() {
	*x = ProcessSummary{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSummary) ProtoMessage() {}

func (x *ProcessSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSummary.ProtoReflect.Descriptor instead.
func (*ProcessSummary) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessSummary) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessSummary) GetExecPath() string {
	if x != nil {
		return x.ExecPath
	}
	return ""
}

func (x *ProcessSummary) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ProcessSummary) GetAncestors() []*AncestorProcess {
	if x != nil {
		return x.Ancestors
	}
	return nil
}

type AncestorProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecPath      string                 `protobuf:"bytes,1,opt,name=exec_path,proto3" json:"exec_path,omitempty"`
	Argv          []string               `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AncestorProcess) Reset() {
	*x = AncestorProcess{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AncestorProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AncestorProcess) ProtoMessage() {}

func (x *AncestorProcess) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AncestorProcess.ProtoReflect.Descriptor instead.
func (*AncestorProcess) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *AncestorProcess) GetExecPath() string {
	if x != nil {
		return x.ExecPath
	}
	return ""
}

func (x *AncestorProcess) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

type ProcessExecPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMemfd       bool                   `protobuf:"varint,1,opt,name=is_memfd,proto3" json:"is_memfd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessExecPayload) Reset() {
	*x = ProcessExecPayload{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessExecPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessExecPayload) ProtoMessage() {}

func (x *ProcessExecPayload) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessExecPayload.ProtoReflect.Descriptor instead.
func (*ProcessExecPayload) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessExecPayload) GetIsMemfd() bool {
	if x != nil {
		return x.IsMemfd
	}
	return false
}

type NetworkConnectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteIp      string                 `protobuf:"bytes,1,opt,name=remote_ip,proto3" json:"remote_ip,omitempty"`
	RemotePort    uint32                 `protobuf:"varint,2,opt,name=remote_port,proto3" json:"remote_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Family        string                 `protobuf:"bytes,4,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConnectPayload) Reset() {
	*x = NetworkConnectPayload{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConnectPayload) ProtoMessage() {}

func (x *NetworkConnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConnectPayload.ProtoReflect.Descriptor instead.
func (*NetworkConnectPayload) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkConnectPayload) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *NetworkConnectPayload) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *NetworkConnectPayload) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkConnectPayload) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

type UnixSocketConnectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SocketType    string                 `protobuf:"bytes,2,opt,name=socket_type,proto3" json:"socket_type,omitempty"`
	IsAbstract    bool                   `protobuf:"varint,3,opt,name=is_abstract,proto3" json:"is_abstract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixSocketConnectPayload) Reset() {
	*x = UnixSocketConnectPayload{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketConnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketConnectPayload) ProtoMessage() {}

func (x *UnixSocketConnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocketConnectPayload.ProtoReflect.Descriptor instead.
func (*UnixSocketConnectPayload) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *UnixSocketConnectPayload) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UnixSocketConnectPayload) GetSocketType() string {
	if x != nil {
		return x.SocketType
	}
	return ""
}

func (x *UnixSocketConnectPayload) GetIsAbstract() bool {
	if x != nil {
		return x.IsAbstract
	}
	return false
}

type FileOpenPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsWrite       bool                   `protobuf:"varint,2,opt,name=is_write,proto3" json:"is_write,omitempty"`
	IsRead        bool                   `protobuf:"varint,3,opt,name=is_read,proto3" json:"is_read,omitempty"`
	Flags         uint64                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOpenPayload) Reset() {
	*x = FileOpenPayload{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOpenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOpenPayload) ProtoMessage() {}

func (x *FileOpenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOpenPayload.ProtoReflect.Descriptor instead.
func (*FileOpenPayload) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *FileOpenPayload) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileOpenPayload) GetIsWrite() bool {
	if x != nil {
		return x.IsWrite
	}
	return false
}

func (x *FileOpenPayload) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *FileOpenPayload) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type FileRemovePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsFolder      bool                   `protobuf:"varint,2,opt,name=is_folder,proto3" json:"is_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRemovePayload) Reset() {
	*x = FileRemovePayload{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRemovePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRemovePayload) ProtoMessage() {}

func (x *FileRemovePayload) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRemovePayload.ProtoReflect.Descriptor instead.
func (*FileRemovePayload) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *FileRemovePayload) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRemovePayload) GetIsFolder() bool {
	if x != nil {
		return x.IsFolder
	}
	return false
}

type FileMovePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPath      string                 `protobuf:"bytes,1,opt,name=from_path,proto3" json:"from_path,omitempty"`
	ToPath        string                 `protobuf:"bytes,2,opt,name=to_path,proto3" json:"to_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMovePayload) Reset() {
	*x = FileMovePayload{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMovePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMovePayload) ProtoMessage() {}

func (x *FileMovePayload) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMovePayload.ProtoReflect.Descriptor instead.
func (*FileMovePayload) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *FileMovePayload) GetFromPath() string {
	if x != nil {
		return x.FromPath
	}
	return ""
}

func (x *FileMovePayload) GetToPath() string {
	if x != nil {
		return x.ToPath
	}
	return ""
}

type FileLinkPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedPath   string                 `protobuf:"bytes,1,opt,name=created_path,proto3" json:"created_path,omitempty"`
	ExistingPath  string                 `protobuf:"bytes,2,opt,name=existing_path,proto3" json:"existing_path,omitempty"`
	IsHardlink    bool                   `protobuf:"varint,3,opt,name=is_hardlink,proto3" json:"is_hardlink,omitempty"`
	IsSymlink     bool                   `protobuf:"varint,4,opt,name=is_symlink,proto3" json:"is_symlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileLinkPayload) Reset() {
	*x = FileLinkPayload{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLinkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLinkPayload) ProtoMessage() {}

func (x *FileLinkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLinkPayload.ProtoReflect.Descriptor instead.
func (*FileLinkPayload) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *FileLinkPayload) GetCreatedPath() string {
	if x != nil {
		return x.CreatedPath
	}
	return ""
}

func (x *FileLinkPayload) GetExistingPath() string {
	if x != nil {
		return x.ExistingPath
	}
	return ""
}

func (x *FileLinkPayload) GetIsHardlink() bool {
	if x != nil {
		return x.IsHardlink
	}
	return false
}

func (x *FileLinkPayload) GetIsSymlink() bool {
	if x != nil {
		return x.IsSymlink
	}
	return false
}

type DomainPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainPayload) Reset() {
	*x = DomainPayload{}
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainPayload) ProtoMessage() {}

func (x *DomainPayload) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainPayload.ProtoReflect.Descriptor instead.
func (*DomainPayload) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *DomainPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainPayload) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_cicd_sensor_log_v1_common_proto protoreflect.FileDescriptor

const file_cicd_sensor_log_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1fcicd_sensor/log/v1/common.proto\x12\x12cicd_sensor.log.v1\"\x8d\x06\n" +
	"\rJobLogContext\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12$\n" +
	"\rprovider_host\x18\x02 \x01(\tR\rprovider_host\x12\"\n" +
	"\fproject_path\x18\x03 \x01(\tR\fproject_path\x12 \n" +
	"\vrunner_kind\x18\x04 \x01(\tR\vrunner_kind\x12\x1a\n" +
	"\bjob_link\x18\x05 \x01(\tR\bjob_link\x12\x1e\n" +
	"\n" +
	"commit_sha\x18\x06 \x01(\tR\n" +
	"commit_sha\x12\x1a\n" +
	"\bref_name\x18\a \x01(\tR\bref_name\x12\x18\n" +
	"\atrigger\x18\b \x01(\tR\atrigger\x12\x1a\n" +
	"\bactor_id\x18\t \x01(\tR\bactor_id\x12\x1e\n" +
	"\n" +
	"actor_name\x18\n" +
	" \x01(\tR\n" +
	"actor_name\x12$\n" +
	"\rgithub_run_id\x18\x14 \x01(\tR\rgithub_run_id\x12\x1e\n" +
	"\n" +
	"github_job\x18\x15 \x01(\tR\n" +
	"github_job\x12.\n" +
	"\x12github_run_attempt\x18\x16 \x01(\tR\x12github_run_attempt\x12<\n" +
	"\x19github_runner_tracking_id\x18\x17 \x01(\tR\x19github_runner_tracking_id\x120\n" +
	"\x13github_workflow_ref\x18\x18 \x01(\tR\x13github_workflow_ref\x120\n" +
	"\x13github_workflow_sha\x18\x19 \x01(\tR\x13github_workflow_sha\x12(\n" +
	"\x0fgithub_workflow\x18\x1a \x01(\tR\x0fgithub_workflow\x12$\n" +
	"\rgitlab_job_id\x18\x1e \x01(\tR\rgitlab_job_id\x12(\n" +
	"\x0fgitlab_job_name\x18\x1f \x01(\tR\x0fgitlab_job_name\x124\n" +
	"\x15gitlab_config_ref_uri\x18  \x01(\tR\x15gitlab_config_ref_uri\"\xd1\x05\n" +
	"\vEventRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12<\n" +
	"\aprocess\x18\x04 \x01(\v2\".cicd_sensor.log.v1.ProcessSummaryR\aprocess\x12J\n" +
	"\fprocess_exec\x18\n" +
	" \x01(\v2&.cicd_sensor.log.v1.ProcessExecPayloadR\fprocess_exec\x12S\n" +
	"\x0fnetwork_connect\x18\v \x01(\v2).cicd_sensor.log.v1.NetworkConnectPayloadR\x0fnetwork_connect\x12^\n" +
	"\x13unix_socket_connect\x18\f \x01(\v2,.cicd_sensor.log.v1.UnixSocketConnectPayloadR\x13unix_socket_connect\x12A\n" +
	"\tfile_open\x18\r \x01(\v2#.cicd_sensor.log.v1.FileOpenPayloadR\tfile_open\x12G\n" +
	"\vfile_remove\x18\x0e \x01(\v2%.cicd_sensor.log.v1.FileRemovePayloadR\vfile_remove\x12A\n" +
	"\tfile_move\x18\x0f \x01(\v2#.cicd_sensor.log.v1.FileMovePayloadR\tfile_move\x12A\n" +
	"\tfile_link\x18\x10 \x01(\v2#.cicd_sensor.log.v1.FileLinkPayloadR\tfile_link\x129\n" +
	"\x06domain\x18\x12 \x01(\v2!.cicd_sensor.log.v1.DomainPayloadR\x06domain\"\x97\x01\n" +
	"\x0eProcessSummary\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x1c\n" +
	"\texec_path\x18\x02 \x01(\tR\texec_path\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\x12A\n" +
	"\tancestors\x18\x04 \x03(\v2#.cicd_sensor.log.v1.AncestorProcessR\tancestors\"C\n" +
	"\x0fAncestorProcess\x12\x1c\n" +
	"\texec_path\x18\x01 \x01(\tR\texec_path\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\"0\n" +
	"\x12ProcessExecPayload\x12\x1a\n" +
	"\bis_memfd\x18\x01 \x01(\bR\bis_memfd\"\x8b\x01\n" +
	"\x15NetworkConnectPayload\x12\x1c\n" +
	"\tremote_ip\x18\x01 \x01(\tR\tremote_ip\x12 \n" +
	"\vremote_port\x18\x02 \x01(\rR\vremote_port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06family\x18\x04 \x01(\tR\x06family\"r\n" +
	"\x18UnixSocketConnectPayload\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12 \n" +
	"\vsocket_type\x18\x02 \x01(\tR\vsocket_type\x12 \n" +
	"\vis_abstract\x18\x03 \x01(\bR\vis_abstract\"q\n" +
	"\x0fFileOpenPayload\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bis_write\x18\x02 \x01(\bR\bis_write\x12\x18\n" +
	"\ais_read\x18\x03 \x01(\bR\ais_read\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\x04R\x05flags\"E\n" +
	"\x11FileRemovePayload\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\tis_folder\x18\x02 \x01(\bR\tis_folder\"I\n" +
	"\x0fFileMovePayload\x12\x1c\n" +
	"\tfrom_path\x18\x01 \x01(\tR\tfrom_path\x12\x18\n" +
	"\ato_path\x18\x02 \x01(\tR\ato_path\"\x9d\x01\n" +
	"\x0fFileLinkPayload\x12\"\n" +
	"\fcreated_path\x18\x01 \x01(\tR\fcreated_path\x12$\n" +
	"\rexisting_path\x18\x02 \x01(\tR\rexisting_path\x12 \n" +
	"\vis_hardlink\x18\x03 \x01(\bR\vis_hardlink\x12\x1e\n" +
	"\n" +
	"is_symlink\x18\x04 \x01(\bR\n" +
	"is_symlink\";\n" +
	"\rDomainPayload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06sourceB\xd7\x01\n" +
	"\x16com.cicd_sensor.log.v1B\vCommonProtoP\x01ZJgithub.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/log/v1;logv1\xa2\x02\x03CLX\xaa\x02\x11CicdSensor.Log.V1\xca\x02\x11CicdSensor\\Log\\V1\xe2\x02\x1dCicdSensor\\Log\\V1\\GPBMetadata\xea\x02\x13CicdSensor::Log::V1b\x06proto3"

var (
	file_cicd_sensor_log_v1_common_proto_rawDescOnce sync.Once
	file_cicd_sensor_log_v1_common_proto_rawDescData []byte
)

func file_cicd_sensor_log_v1_common_proto_rawDescGZIP() []byte {
	file_cicd_sensor_log_v1_common_proto_rawDescOnce.Do(func() {
		file_cicd_sensor_log_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cicd_sensor_log_v1_common_proto_rawDesc), len(file_cicd_sensor_log_v1_common_proto_rawDesc)))
	})
	return file_cicd_sensor_log_v1_common_proto_rawDescData
}

var file_cicd_sensor_log_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cicd_sensor_log_v1_common_proto_goTypes = []any{
	(*JobLogContext)(nil),            // 0: cicd_sensor.log.v1.JobLogContext
	(*EventRecord)(nil),              // 1: cicd_sensor.log.v1.EventRecord
	(*ProcessSummary)(nil),           // 2: cicd_sensor.log.v1.ProcessSummary
	(*AncestorProcess)(nil),          // 3: cicd_sensor.log.v1.AncestorProcess
	(*ProcessExecPayload)(nil),       // 4: cicd_sensor.log.v1.ProcessExecPayload
	(*NetworkConnectPayload)(nil),    // 5: cicd_sensor.log.v1.NetworkConnectPayload
	(*UnixSocketConnectPayload)(nil), // 6: cicd_sensor.log.v1.UnixSocketConnectPayload
	(*FileOpenPayload)(nil),          // 7: cicd_sensor.log.v1.FileOpenPayload
	(*FileRemovePayload)(nil),        // 8: cicd_sensor.log.v1.FileRemovePayload
	(*FileMovePayload)(nil),          // 9: cicd_sensor.log.v1.FileMovePayload
	(*FileLinkPayload)(nil),          // 10: cicd_sensor.log.v1.FileLinkPayload
	(*DomainPayload)(nil),            // 11: cicd_sensor.log.v1.DomainPayload
}
var file_cicd_sensor_log_v1_common_proto_depIdxs = []int32{
	2,  // 0: cicd_sensor.log.v1.EventRecord.process:type_name -> cicd_sensor.log.v1.ProcessSummary
	4,  // 1: cicd_sensor.log.v1.EventRecord.process_exec:type_name -> cicd_sensor.log.v1.ProcessExecPayload
	5,  // 2: cicd_sensor.log.v1.EventRecord.network_connect:type_name -> cicd_sensor.log.v1.NetworkConnectPayload
	6,  // 3: cicd_sensor.log.v1.EventRecord.unix_socket_connect:type_name -> cicd_sensor.log.v1.UnixSocketConnectPayload
	7,  // 4: cicd_sensor.log.v1.EventRecord.file_open:type_name -> cicd_sensor.log.v1.FileOpenPayload
	8,  // 5: cicd_sensor.log.v1.EventRecord.file_remove:type_name -> cicd_sensor.log.v1.FileRemovePayload
	9,  // 6: cicd_sensor.log.v1.EventRecord.file_move:type_name -> cicd_sensor.log.v1.FileMovePayload
	10, // 7: cicd_sensor.log.v1.EventRecord.file_link:type_name -> cicd_sensor.log.v1.FileLinkPayload
	11, // 8: cicd_sensor.log.v1.EventRecord.domain:type_name -> cicd_sensor.log.v1.DomainPayload
	3,  // 9: cicd_sensor.log.v1.ProcessSummary.ancestors:type_name -> cicd_sensor.log.v1.AncestorProcess
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cicd_sensor_log_v1_common_proto_init() }
func file_cicd_sensor_log_v1_common_proto_init() {
	if File_cicd_sensor_log_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cicd_sensor_log_v1_common_proto_rawDesc), len(file_cicd_sensor_log_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cicd_sensor_log_v1_common_proto_goTypes,
		DependencyIndexes: file_cicd_sensor_log_v1_common_proto_depIdxs,
		MessageInfos:      file_cicd_sensor_log_v1_common_proto_msgTypes,
	}.Build()
	File_cicd_sensor_log_v1_common_proto = out.File
	file_cicd_sensor_log_v1_common_proto_goTypes = nil
	file_cicd_sensor_log_v1_common_proto_depIdxs = nil
}
