// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cicd_sensor/log/v1/detection.proto

package logv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobDetectionLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogType       *string                `protobuf:"bytes,2,opt,name=log_type,proto3,oneof" json:"log_type,omitempty"`
	SchemaVersion *string                `protobuf:"bytes,3,opt,name=schema_version,proto3,oneof" json:"schema_version,omitempty"`
	AgentVersion  *string                `protobuf:"bytes,4,opt,name=agent_version,proto3,oneof" json:"agent_version,omitempty"`
	// UUIDv7 for this detection log row.
	LogId               *string        `protobuf:"bytes,5,opt,name=log_id,proto3,oneof" json:"log_id,omitempty"`
	Job                 *JobLogContext `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	Scope               *string        `protobuf:"bytes,7,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	RunnerKind          *string        `protobuf:"bytes,8,opt,name=runner_kind,proto3,oneof" json:"runner_kind,omitempty"`
	RulesetId           *string        `protobuf:"bytes,9,opt,name=ruleset_id,proto3,oneof" json:"ruleset_id,omitempty"`
	RuleId              *string        `protobuf:"bytes,10,opt,name=rule_id,proto3,oneof" json:"rule_id,omitempty"`
	RulesetRevision     *string        `protobuf:"bytes,11,opt,name=ruleset_revision,proto3,oneof" json:"ruleset_revision,omitempty"`
	RuleName            *string        `protobuf:"bytes,12,opt,name=rule_name,proto3,oneof" json:"rule_name,omitempty"`
	RuleDescription     *string        `protobuf:"bytes,13,opt,name=rule_description,proto3,oneof" json:"rule_description,omitempty"`
	Action              *string        `protobuf:"bytes,14,opt,name=action,proto3,oneof" json:"action,omitempty"`
	RuleAlertTruncation *string        `protobuf:"bytes,15,opt,name=rule_alert_truncation,proto3,oneof" json:"rule_alert_truncation,omitempty"`
	Event               *EventRecord   `protobuf:"bytes,16,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *JobDetectionLogEntry) Reset() {
	*x = JobDetectionLogEntry{}
	mi := &file_cicd_sensor_log_v1_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetectionLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetectionLogEntry) ProtoMessage() {}

func (x *JobDetectionLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetectionLogEntry.ProtoReflect.Descriptor instead.
func (*JobDetectionLogEntry) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_detection_proto_rawDescGZIP(), []int{0}
}

func (x *JobDetectionLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *JobDetectionLogEntry) GetLogType() string {
	if x != nil && x.LogType != nil {
		return *x.LogType
	}
	return ""
}

func (x *JobDetectionLogEntry) GetSchemaVersion() string {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return ""
}

func (x *JobDetectionLogEntry) GetAgentVersion() string {
	if x != nil && x.AgentVersion != nil {
		return *x.AgentVersion
	}
	return ""
}

func (x *JobDetectionLogEntry) GetLogId() string {
	if x != nil && x.LogId != nil {
		return *x.LogId
	}
	return ""
}

func (x *JobDetectionLogEntry) GetJob() *JobLogContext {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *JobDetectionLogEntry) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *JobDetectionLogEntry) GetRunnerKind() string {
	if x != nil && x.RunnerKind != nil {
		return *x.RunnerKind
	}
	return ""
}

func (x *JobDetectionLogEntry) GetRulesetId() string {
	if x != nil && x.RulesetId != nil {
		return *x.RulesetId
	}
	return ""
}

func (x *JobDetectionLogEntry) GetRuleId() string {
	if x != nil && x.RuleId != nil {
		return *x.RuleId
	}
	return ""
}

func (x *JobDetectionLogEntry) GetRulesetRevision() string {
	if x != nil && x.RulesetRevision != nil {
		return *x.RulesetRevision
	}
	return ""
}

func (x *JobDetectionLogEntry) GetRuleName() string {
	if x != nil && x.RuleName != nil {
		return *x.RuleName
	}
	return ""
}

func (x *JobDetectionLogEntry) GetRuleDescription() string {
	if x != nil && x.RuleDescription != nil {
		return *x.RuleDescription
	}
	return ""
}

func (x *JobDetectionLogEntry) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *JobDetectionLogEntry) GetRuleAlertTruncation() string {
	if x != nil && x.RuleAlertTruncation != nil {
		return *x.RuleAlertTruncation
	}
	return ""
}

func (x *JobDetectionLogEntry) GetEvent() *EventRecord {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_cicd_sensor_log_v1_detection_proto protoreflect.FileDescriptor

const file_cicd_sensor_log_v1_detection_proto_rawDesc = "" +
	"\n" +
	"\"cicd_sensor/log/v1/detection.proto\x12\x12cicd_sensor.log.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fcicd_sensor/log/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\a\n" +
	"\x14JobDetectionLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\blog_type\x18\x02 \x01(\tH\x00R\blog_type\x88\x01\x01\x126\n" +
	"\x0eschema_version\x18\x03 \x01(\tB\t\xbaH\x06r\x04\n" +
	"\x02v1H\x01R\x0eschema_version\x88\x01\x01\x12)\n" +
	"\ragent_version\x18\x04 \x01(\tH\x02R\ragent_version\x88\x01\x01\x12\x1b\n" +
	"\x06log_id\x18\x05 \x01(\tH\x03R\x06log_id\x88\x01\x01\x123\n" +
	"\x03job\x18\x06 \x01(\v2!.cicd_sensor.log.v1.JobLogContextR\x03job\x12\x19\n" +
	"\x05scope\x18\a \x01(\tH\x04R\x05scope\x88\x01\x01\x12%\n" +
	"\vrunner_kind\x18\b \x01(\tH\x05R\vrunner_kind\x88\x01\x01\x12#\n" +
	"\n" +
	"ruleset_id\x18\t \x01(\tH\x06R\n" +
	"ruleset_id\x88\x01\x01\x12\x1d\n" +
	"\arule_id\x18\n" +
	" \x01(\tH\aR\arule_id\x88\x01\x01\x12/\n" +
	"\x10ruleset_revision\x18\v \x01(\tH\bR\x10ruleset_revision\x88\x01\x01\x12!\n" +
	"\trule_name\x18\f \x01(\tH\tR\trule_name\x88\x01\x01\x12/\n" +
	"\x10rule_description\x18\r \x01(\tH\n" +
	"R\x10rule_description\x88\x01\x01\x12\x1b\n" +
	"\x06action\x18\x0e \x01(\tH\vR\x06action\x88\x01\x01\x129\n" +
	"\x15rule_alert_truncation\x18\x0f \x01(\tH\fR\x15rule_alert_truncation\x88\x01\x01\x125\n" +
	"\x05event\x18\x10 \x01(\v2\x1f.cicd_sensor.log.v1.EventRecordR\x05eventB\v\n" +
	"\t_log_typeB\x11\n" +
	"\x0f_schema_versionB\x10\n" +
	"\x0e_agent_versionB\t\n" +
	"\a_log_idB\b\n" +
	"\x06_scopeB\x0e\n" +
	"\f_runner_kindB\r\n" +
	"\v_ruleset_idB\n" +
	"\n" +
	"\b_rule_idB\x13\n" +
	"\x11_ruleset_revisionB\f\n" +
	"\n" +
	"_rule_nameB\x13\n" +
	"\x11_rule_descriptionB\t\n" +
	"\a_actionB\x18\n" +
	"\x16_rule_alert_truncationB\xda\x01\n" +
	"\x16com.cicd_sensor.log.v1B\x0eDetectionProtoP\x01ZJgithub.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/log/v1;logv1\xa2\x02\x03CLX\xaa\x02\x11CicdSensor.Log.V1\xca\x02\x11CicdSensor\\Log\\V1\xe2\x02\x1dCicdSensor\\Log\\V1\\GPBMetadata\xea\x02\x13CicdSensor::Log::V1b\x06proto3"

var (
	file_cicd_sensor_log_v1_detection_proto_rawDescOnce sync.Once
	file_cicd_sensor_log_v1_detection_proto_rawDescData []byte
)

func file_cicd_sensor_log_v1_detection_proto_rawDescGZIP() []byte {
	file_cicd_sensor_log_v1_detection_proto_rawDescOnce.Do(func() {
		file_cicd_sensor_log_v1_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cicd_sensor_log_v1_detection_proto_rawDesc), len(file_cicd_sensor_log_v1_detection_proto_rawDesc)))
	})
	return file_cicd_sensor_log_v1_detection_proto_rawDescData
}

var file_cicd_sensor_log_v1_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cicd_sensor_log_v1_detection_proto_goTypes = []any{
	(*JobDetectionLogEntry)(nil),  // 0: cicd_sensor.log.v1.JobDetectionLogEntry
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*JobLogContext)(nil),         // 2: cicd_sensor.log.v1.JobLogContext
	(*EventRecord)(nil),           // 3: cicd_sensor.log.v1.EventRecord
}
var file_cicd_sensor_log_v1_detection_proto_depIdxs = []int32{
	1, // 0: cicd_sensor.log.v1.JobDetectionLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: cicd_sensor.log.v1.JobDetectionLogEntry.job:type_name -> cicd_sensor.log.v1.JobLogContext
	3, // 2: cicd_sensor.log.v1.JobDetectionLogEntry.event:type_name -> cicd_sensor.log.v1.EventRecord
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cicd_sensor_log_v1_detection_proto_init() }
func file_cicd_sensor_log_v1_detection_proto_init() {
	if File_cicd_sensor_log_v1_detection_proto != nil {
		return
	}
	file_cicd_sensor_log_v1_common_proto_init()
	file_cicd_sensor_log_v1_detection_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cicd_sensor_log_v1_detection_proto_rawDesc), len(file_cicd_sensor_log_v1_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cicd_sensor_log_v1_detection_proto_goTypes,
		DependencyIndexes: file_cicd_sensor_log_v1_detection_proto_depIdxs,
		MessageInfos:      file_cicd_sensor_log_v1_detection_proto_msgTypes,
	}.Build()
	File_cicd_sensor_log_v1_detection_proto = out.File
	file_cicd_sensor_log_v1_detection_proto_goTypes = nil
	file_cicd_sensor_log_v1_detection_proto_depIdxs = nil
}
