// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cicd_sensor/log/v1/runtime_telemetry.proto

package logv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRuntimeTelemetryLogEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// UUIDv7 for this runtime telemetry log row.
	LogId          *string        `protobuf:"bytes,2,opt,name=log_id,proto3,oneof" json:"log_id,omitempty"`
	Job            *JobLogContext `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	Scope          *string        `protobuf:"bytes,4,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	ConfigRevision *string        `protobuf:"bytes,5,opt,name=config_revision,proto3,oneof" json:"config_revision,omitempty"`
	Event          *EventRecord   `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobRuntimeTelemetryLogEntry) Reset() {
	*x = JobRuntimeTelemetryLogEntry{}
	mi := &file_cicd_sensor_log_v1_runtime_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRuntimeTelemetryLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRuntimeTelemetryLogEntry) ProtoMessage() {}

func (x *JobRuntimeTelemetryLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_log_v1_runtime_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRuntimeTelemetryLogEntry.ProtoReflect.Descriptor instead.
func (*JobRuntimeTelemetryLogEntry) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *JobRuntimeTelemetryLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *JobRuntimeTelemetryLogEntry) GetLogId() string {
	if x != nil && x.LogId != nil {
		return *x.LogId
	}
	return ""
}

func (x *JobRuntimeTelemetryLogEntry) GetJob() *JobLogContext {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *JobRuntimeTelemetryLogEntry) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *JobRuntimeTelemetryLogEntry) GetConfigRevision() string {
	if x != nil && x.ConfigRevision != nil {
		return *x.ConfigRevision
	}
	return ""
}

func (x *JobRuntimeTelemetryLogEntry) GetEvent() *EventRecord {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_cicd_sensor_log_v1_runtime_telemetry_proto protoreflect.FileDescriptor

const file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDesc = "" +
	"\n" +
	"*cicd_sensor/log/v1/runtime_telemetry.proto\x12\x12cicd_sensor.log.v1\x1a\x1fcicd_sensor/log/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x02\n" +
	"\x1bJobRuntimeTelemetryLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\x06log_id\x18\x02 \x01(\tH\x00R\x06log_id\x88\x01\x01\x123\n" +
	"\x03job\x18\x03 \x01(\v2!.cicd_sensor.log.v1.JobLogContextR\x03job\x12\x19\n" +
	"\x05scope\x18\x04 \x01(\tH\x01R\x05scope\x88\x01\x01\x12-\n" +
	"\x0fconfig_revision\x18\x05 \x01(\tH\x02R\x0fconfig_revision\x88\x01\x01\x125\n" +
	"\x05event\x18\a \x01(\v2\x1f.cicd_sensor.log.v1.EventRecordR\x05eventB\t\n" +
	"\a_log_idB\b\n" +
	"\x06_scopeB\x12\n" +
	"\x10_config_revisionB\xe1\x01\n" +
	"\x16com.cicd_sensor.log.v1B\x15RuntimeTelemetryProtoP\x01ZJgithub.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/log/v1;logv1\xa2\x02\x03CLX\xaa\x02\x11CicdSensor.Log.V1\xca\x02\x11CicdSensor\\Log\\V1\xe2\x02\x1dCicdSensor\\Log\\V1\\GPBMetadata\xea\x02\x13CicdSensor::Log::V1b\x06proto3"

var (
	file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDescOnce sync.Once
	file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDescData []byte
)

func file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDescGZIP() []byte {
	file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDescOnce.Do(func() {
		file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDesc), len(file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDesc)))
	})
	return file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDescData
}

var file_cicd_sensor_log_v1_runtime_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cicd_sensor_log_v1_runtime_telemetry_proto_goTypes = []any{
	(*JobRuntimeTelemetryLogEntry)(nil), // 0: cicd_sensor.log.v1.JobRuntimeTelemetryLogEntry
	(*timestamppb.Timestamp)(nil),       // 1: google.protobuf.Timestamp
	(*JobLogContext)(nil),               // 2: cicd_sensor.log.v1.JobLogContext
	(*EventRecord)(nil),                 // 3: cicd_sensor.log.v1.EventRecord
}
var file_cicd_sensor_log_v1_runtime_telemetry_proto_depIdxs = []int32{
	1, // 0: cicd_sensor.log.v1.JobRuntimeTelemetryLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: cicd_sensor.log.v1.JobRuntimeTelemetryLogEntry.job:type_name -> cicd_sensor.log.v1.JobLogContext
	3, // 2: cicd_sensor.log.v1.JobRuntimeTelemetryLogEntry.event:type_name -> cicd_sensor.log.v1.EventRecord
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cicd_sensor_log_v1_runtime_telemetry_proto_init() }
func file_cicd_sensor_log_v1_runtime_telemetry_proto_init() {
	if File_cicd_sensor_log_v1_runtime_telemetry_proto != nil {
		return
	}
	file_cicd_sensor_log_v1_common_proto_init()
	file_cicd_sensor_log_v1_runtime_telemetry_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDesc), len(file_cicd_sensor_log_v1_runtime_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cicd_sensor_log_v1_runtime_telemetry_proto_goTypes,
		DependencyIndexes: file_cicd_sensor_log_v1_runtime_telemetry_proto_depIdxs,
		MessageInfos:      file_cicd_sensor_log_v1_runtime_telemetry_proto_msgTypes,
	}.Build()
	File_cicd_sensor_log_v1_runtime_telemetry_proto = out.File
	file_cicd_sensor_log_v1_runtime_telemetry_proto_goTypes = nil
	file_cicd_sensor_log_v1_runtime_telemetry_proto_depIdxs = nil
}
